import type { GamePhase, KnowledgeDomain } from '../types/game.ts';
import type { ActiveEventAllocationV2, ActiveEventV2, GameSessionV2 } from '../types/gameV2.ts';
import { DEFAULT_CONFIG } from '../engine/config.ts';
import { calculateCardImpact } from '../engine/cards.ts';
import { PROGRAMMED_FAILURE_TAG, applyProgressionToCurrentEvents, capProgressedEventImpact, diversifyInitialKnowledge, progressEventCard } from '../engine/eventProgressionV5.ts';
import { drawRoundEventsV2, recalculateCompanySPOFV2 } from '../engine/coreV2.ts';
import { executeRiverKnowledgeSharing } from '../engine/riverKnowledgeV1.ts';
import { applyInterfaceSimplificationV1 } from '../engine/interfaceSimplificationV1.ts';
import { saveSessionV2 } from './dbV2.ts';
import type { CreateGameOptions } from './gameServiceV4.ts';
import { broadcastV2 } from './gameServiceV2.ts';
import { advancePhaseV2 as baseAdvancePhaseV2, createNewSessionV2 as baseCreateNewSessionV2, getSessionV2 as baseGetSessionV2, initializeDefaultSessionV2 as baseInitializeDefaultSessionV2, knowledgeActionV2 as baseKnowledgeActionV2, redrawEventV2 as baseRedrawEventV2, resolveEventV2 as baseResolveEventV2, resolveFinalDisruptionV2 as baseResolveFinalDisruptionV2, setEventAllocationV2 as baseSetEventAllocationV2 } from './gameServiceV4.ts';
export * from './gameServiceV4.ts';

function ensureProgressionConfig(session:GameSessionV2):void{session.config.event_value_growth_factor??=DEFAULT_CONFIG.event_value_growth_factor;session.config.event_difficulty_growth_per_move??=DEFAULT_CONFIG.event_difficulty_growth_per_move;session.config.event_initial_impact_multiplier??=DEFAULT_CONFIG.event_initial_impact_multiplier;session.config.event_impact_cap_ratio??=DEFAULT_CONFIG.event_impact_cap_ratio;session.config.event_difficulty_cap??=DEFAULT_CONFIG.event_difficulty_cap;session.config.event_expert_moves_per_pressure_step??=DEFAULT_CONFIG.event_expert_moves_per_pressure_step;}
function isProgrammedFailure(event:any):boolean{return Boolean(event?.card?.tags?.includes(PROGRAMMED_FAILURE_TAG));}
function freshAllocations(event:ActiveEventV2):any{const allocations:any={};for(const requirement of event.card.domains)allocations[requirement.domain]={};return allocations;}
function normaliseOpeningTutorial(session:GameSessionV2):void{for(const company of session.companies){for(const event of session.activeEvents[company.id]||[]){if(!isProgrammedFailure(event))continue;event.card.domains=event.card.domains.map((req:any)=>({...req,difficulty:5}));event.card.description=event.card.description.replace('— but that knowledge is not yet available here through the Corporate Intranet.','. The Corporate Intranet may also contain useful knowledge that this site can apply.');}}}
function applyFreshGameModel(session:GameSessionV2):void{ensureProgressionConfig(session);for(const company of session.companies){diversifyInitialKnowledge(company);recalculateCompanySPOFV2(company,session.config);applyProgressionToCurrentEvents(session,company);}normaliseOpeningTutorial(session);applyInterfaceSimplificationV1(session);}
function looksLikeUnstartedGame(session:GameSessionV2):boolean{return session.round===1&&session.companies.every(company=>{const events=session.activeEvents[company.id]||[];return events.length>0&&events.every(event=>!event.isResolved&&!/^(LEARNING|MATERIAL|HIGH STAKES|CRITICAL):/.test(event.card.title));});}
function tutorialAllocationAllowed(allocation:ActiveEventAllocationV2):boolean{return !allocation.expertId&&!allocation.useCoPSupport&&Math.max(0,allocation.consultantPoints||0)===0;}
function scaleFinalDisruptionToRoundsPlayed(session:GameSessionV2):void{const card=session.finalDisruptionCard;if(!card||card.tags?.includes('round-scaled-final'))return;const designRound=8;const completedRounds=Math.max(1,session.round);const progress=Math.max(0,Math.min(1,(completedRounds-1)/(designRound-1)));card.domains=card.domains.map(requirement=>{const floor=Math.max(3,requirement.difficulty-5);const scaled=Math.round(floor+(requirement.difficulty-floor)*progress);return{...requirement,difficulty:Math.max(floor,Math.min(requirement.difficulty,scaled))};});card.impact=calculateCardImpact(card);card.tags=[...(card.tags||[]),'round-scaled-final',`final-round:${completedRounds}`];card.description=`${card.description} The scale of this final test reflects how many rounds your company had to build capability.`;applyInterfaceSimplificationV1(session);}

export async function createNewSessionV2(sessionId:string,title:string,companyNames:string[]=['Apex Technologies'],options:CreateGameOptions={}):Promise<GameSessionV2>{
 const session=await baseCreateNewSessionV2(sessionId,title,companyNames,options);
 if(session.experienceMode==='expert'&&session.config.events_per_round<3){
  session.config.events_per_round=1;
  for(const company of session.companies)session.activeEvents[company.id]=[...(session.activeEvents[company.id]||[]),...drawRoundEventsV2(session,company)];
  session.config.events_per_round=3;
 }
 applyFreshGameModel(session);await saveSessionV2(session);broadcastV2(session,'SESSION_PROGRESSIVE_BALANCE_APPLIED',{valueGrowthFactor:session.config.event_value_growth_factor,difficultyGrowthPerMove:session.config.event_difficulty_growth_per_move,impactCapRatio:session.config.event_impact_cap_ratio,expertMovesPerPressureStep:session.config.event_expert_moves_per_pressure_step});return session;
}
export async function initializeDefaultSessionV2():Promise<GameSessionV2>{const session=await baseInitializeDefaultSessionV2();ensureProgressionConfig(session);if(looksLikeUnstartedGame(session))applyFreshGameModel(session);else{normaliseOpeningTutorial(session);applyInterfaceSimplificationV1(session);}await saveSessionV2(session);return session;}
export async function knowledgeActionV2(sessionId:string,companyId:string,payload:any){const session=await baseGetSessionV2(sessionId.toUpperCase());if(session?.experienceMode==='newbie'&&payload?.domain==='finance')return{success:false,message:'Finance is not a knowledge domain in Newbie mode.',session};if(payload?.type!=='SITE_KNOWLEDGE_SHARING')return baseKnowledgeActionV2(sessionId,companyId,payload);if(!session)return{success:false,message:'Session not found.'};const company=session.companies.find(c=>c.id===companyId);if(!company)return{success:false,message:'Company not found.',session};const result=executeRiverKnowledgeSharing(session,company,payload);if(!result.success)return result;applyInterfaceSimplificationV1(session);await saveSessionV2(session);broadcastV2(session,'RIVER_KNOWLEDGE_SHARED',{companyId,sourceSiteId:payload.sourceSiteId,targetSiteId:payload.siteId,domain:payload.domain});return result;}
export async function setEventAllocationV2(sessionId:string,companyId:string,eventInstanceId:string,domain:KnowledgeDomain,allocation:ActiveEventAllocationV2){const session=await baseGetSessionV2(sessionId.toUpperCase());if(session?.experienceMode==='newbie'&&domain==='finance')return{success:false,message:'Finance is not a knowledge domain in Newbie mode.',session};const company=session?.companies.find(c=>c.id===companyId);const event=company?(session?.activeEvents[company.id]||[]).find(item=>item.instanceId===eventInstanceId):undefined;if(event&&isProgrammedFailure(event)&&!tutorialAllocationAllowed(allocation))return{success:false,message:'Opening learning challenge: use the local team and, if useful, the Corporate Intranet. Experts, networks, favours and consultants are deliberately unavailable for this first challenge.',session};return baseSetEventAllocationV2(sessionId,companyId,eventInstanceId,domain,allocation);}
export async function resolveEventV2(sessionId:string,companyId:string,eventInstanceId?:string){const before=await baseGetSessionV2(sessionId.toUpperCase());const company=before?.companies.find(c=>c.id===companyId);const event=company?(before?.activeEvents[company.id]||[]).find(e=>eventInstanceId?e.instanceId===eventInstanceId:!e.isResolved):undefined;if(!before||!event||!isProgrammedFailure(event))return baseResolveEventV2(sessionId,companyId,eventInstanceId);const original=new Map<KnowledgeDomain,number>(event.card.domains.map(req=>[req.domain,req.difficulty]));event.card.domains=event.card.domains.map(req=>({...req,difficulty:99}));await saveSessionV2(before);const result:any=await baseResolveEventV2(sessionId,companyId,eventInstanceId);if(!result?.session)return result;const resultCompany=result.session.companies.find((c:any)=>c.id===companyId);const resultEvent=resultCompany?(result.session.activeEvents[resultCompany.id]||[]).find((e:any)=>e.instanceId===event.instanceId):undefined;if(resultEvent){resultEvent.card.domains=resultEvent.card.domains.map((req:any)=>({...req,difficulty:original.get(req.domain)??5}));if(Array.isArray(resultEvent.domainResults))resultEvent.domainResults=resultEvent.domainResults.map((r:any)=>{const difficulty=original.get(r.domain)??5;const totalKnowledge=Math.max(0,Number(r.totalKnowledge)||0);return{...r,dieRoll:1,domainSuccess:false,difficulty,requiredTotal:difficulty+result.session.config.resolution_offset,achievedTotal:1+totalKnowledge,explanation:`Selected knowledge ${totalKnowledge}; rolled 1; needed ${difficulty+result.session.config.resolution_offset}.`};});}if(result.result){result.result.success=false;if(Array.isArray(result.result.domainResults))result.result.domainResults=result.result.domainResults.map((r:any)=>{const difficulty=original.get(r.domain)??5;const totalKnowledge=Math.max(0,Number(r.totalKnowledge)||0);return{...r,dieRoll:1,domainSuccess:false,difficulty,requiredTotal:difficulty+result.session.config.resolution_offset,achievedTotal:1+totalKnowledge,explanation:`Selected knowledge ${totalKnowledge}; rolled 1; needed ${difficulty+result.session.config.resolution_offset}.`};});}result.eventSuccess=false;await saveSessionV2(result.session);broadcastV2(result.session,'TUTORIAL_PROGRAMMED_FAILURE',{companyId,eventInstanceId:event.instanceId});return result;}

export async function delayEventV2(sessionId:string,companyId:string,eventInstanceId:string){
 const session=await baseGetSessionV2(sessionId.toUpperCase());if(!session)return{success:false,message:'Session not found.'};
 const company=session.companies.find(c=>c.id===companyId);if(!company)return{success:false,message:'Company not found.',session};
 if(session.phase!=='respond')return{success:false,message:'Events can only be delayed during the Event phase.',session};
 if(company.delayedEvent)return{success:false,message:'Only one Event can be delayed at a time.',session};
 if(company.horizonScanAvailableRound!==session.round||company.horizonScanUsedThisRound||!company.horizonScanDomain)return{success:false,message:'No unused Horizon Scan is available this round.',session};
 const events=session.activeEvents[company.id]||[];const index=events.findIndex(event=>event.instanceId===eventInstanceId);if(index<0)return{success:false,message:'Event not found.',session};
 const event=events[index];if(event.isResolved)return{success:false,message:'A resolved Event cannot be delayed.',session};
 const matches=event.card.domains.some(req=>req.domain===company.horizonScanDomain);
 if(session.experienceMode==='expert'&&!matches)return{success:false,message:`Expert mode can only delay an Event matching the scanned ${company.horizonScanDomain} domain.`,session};
 company.delayedEvent={...event,delayedFromRound:session.round,isResolved:false,allocations:freshAllocations(event)};
 events.splice(index,1);company.horizonScanUsedThisRound=true;
 applyInterfaceSimplificationV1(session);await saveSessionV2(session);broadcastV2(session,'HORIZON_SCAN_EVENT_DELAYED',{companyId,eventInstanceId,cardTitle:event.card.title,returnRound:session.round+1});
 return{success:true,message:`“${event.card.title}” delayed until next round.`,session};
}

export async function redrawEventV2(sessionId:string,companyId:string,eventInstanceId:string){const session=await baseGetSessionV2(sessionId.toUpperCase());const companyBefore=session?.companies.find(c=>c.id===companyId);const eventBefore=companyBefore?(session?.activeEvents[companyBefore.id]||[]).find(event=>event.instanceId===eventInstanceId):undefined;if(eventBefore&&isProgrammedFailure(eventBefore))return{success:false,message:'The opening learning challenge cannot be redrawn.',session};const result=await baseRedrawEventV2(sessionId,companyId,eventInstanceId);if(!result.success)return result;ensureProgressionConfig(result.session);const company=result.session.companies.find(c=>c.id===companyId);const events=company?(result.session.activeEvents[company.id]||[]):[];const eventIndex=events.findIndex(event=>event.instanceId===eventInstanceId);if(company&&eventIndex>=0){const firstMove=Math.max(1,company.eventsDrawnCount-events.length+1);const event=events[eventIndex];event.card=progressEventCard(event.card,firstMove+eventIndex,result.session.config,result.session.experienceMode);event.card=capProgressedEventImpact(event.card,company,event.targetSiteId,result.session.config);const allocations:Partial<Record<KnowledgeDomain,any>>={};event.card.domains.forEach(req=>{allocations[req.domain]=event.allocations?.[req.domain]||{};});event.allocations=allocations as any;applyInterfaceSimplificationV1(result.session);await saveSessionV2(result.session);broadcastV2(result.session,'HORIZON_SCAN_REDRAW_ESCALATED',{companyId,eventInstanceId});}return result;}

export async function advancePhaseV2(sessionId:string,requested?:GamePhase){
 const before=await baseGetSessionV2(sessionId.toUpperCase());
 const delayedBefore=new Map<string,ActiveEventV2>();for(const company of before?.companies||[])if(company.delayedEvent)delayedBefore.set(company.id,company.delayedEvent);
 const result=await baseAdvancePhaseV2(sessionId,requested);
 if(result.success&&result.session.isFinalDisruptionActive&&!result.session.finalDisruptionResolved){scaleFinalDisruptionToRoundsPlayed(result.session);applyInterfaceSimplificationV1(result.session);await saveSessionV2(result.session);broadcastV2(result.session,'FINAL_DISRUPTION_SCALED',{round:result.session.round,domains:result.session.finalDisruptionCard?.domains});return result;}
 if(result.success&&result.session.phase==='respond'&&!result.session.isFinalDisruptionActive){
  ensureProgressionConfig(result.session);
  for(const company of result.session.companies){const events=result.session.activeEvents[company.id]||[];if(events.length&&events.every(event=>!event.isResolved))applyProgressionToCurrentEvents(result.session,company);const delayed=delayedBefore.get(company.id);if(delayed&&result.session.round>(delayed.delayedFromRound||0)){const returning:ActiveEventV2={...delayed,instanceId:`delayed-${result.session.round}-${Math.random().toString(36).slice(2,8)}`,isResolved:false,success:undefined,domainResults:undefined,turnoverChangeApplied:undefined,resolvedAt:undefined,allocations:freshAllocations(delayed)};if(events.length)events[0]=returning;else events.push(returning);company.delayedEvent=null;}}
  normaliseOpeningTutorial(result.session);applyInterfaceSimplificationV1(result.session);await saveSessionV2(result.session);broadcastV2(result.session,'ROUND_EVENTS_ESCALATED',{round:result.session.round});
 }
 return result;
}
export async function resolveFinalDisruptionV2(sessionId:string){const existing=await baseGetSessionV2(sessionId.toUpperCase());if(existing&&!existing.finalDisruptionResolved){scaleFinalDisruptionToRoundsPlayed(existing);applyInterfaceSimplificationV1(existing);await saveSessionV2(existing);}const result=await baseResolveFinalDisruptionV2(sessionId);if(result?.success&&result.session){(result.session as any).finalDisruptionResults=result.results||[];applyInterfaceSimplificationV1(result.session);await saveSessionV2(result.session);broadcastV2(result.session,'FINAL_DISRUPTION_RESULTS_STORED',{results:result.results||[]});}return result;}
