import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,ArrowRight,CheckCircle2,Lightbulb,ShieldAlert,UserCheck,UserX,Users}from'lucide-react';
import type{KnowledgeDomain}from'../types/game.ts';
import{DOMAIN_INFO}from'../types/game.ts';
import type{CompanyV2,GameSessionV2}from'../types/gameV2.ts';
import{RiskRiverDiagram,type RiskRiverEffect}from'./RiskRiverDiagram.tsx';

interface AttritionModalProps{session:GameSessionV2;company:CompanyV2;phaseResult:any;onAdvanceToNextRound:()=>void;onSessionUpdate?:(session:GameSessionV2)=>void;}
type RiskCard={id:string;kind:'expert-departed'|'expert-retained'|'workforce-loss'|'workforce-stable';title:string;location?:string;domainLines?:string[];detail:string;detailDomain?:string;impact:string;roll?:number;warning?:string;hint?:string;effect:RiskRiverEffect;};

export const AttritionModal:React.FC<AttritionModalProps>=({session,company,phaseResult,onAdvanceToNextRound,onSessionUpdate})=>{
 const[currentIndex,setCurrentIndex]=useState(0),[placing,setPlacing]=useState<string|null>(null),[placementError,setPlacementError]=useState(''),[replacementEffect,setReplacementEffect]=useState<RiskRiverEffect>(null);
 const summary=phaseResult?.attritionSummaries?.[company.id]||{expertChecks:[],siteChecks:[],departedExperts:[],workforceAttrition:[],closedSites:[]};
 const placementKey=(expertId:string)=>`tpg_replacement_base_${session.id}_${company.id}_r${session.round}_${expertId}`;
 const[placements,setPlacements]=useState<Record<string,string>>(()=>Object.fromEntries((summary.departedExperts||[]).map((d:any)=>[d.expertId,localStorage.getItem(placementKey(d.expertId))||''])));
 const cards=useMemo<RiskCard[]>(()=>{
  const departedById=new Map(summary.departedExperts.map((entry:any)=>[entry.expertId,entry]));
  const expertChecks=Array.isArray(summary.expertChecks)&&summary.expertChecks.length?summary.expertChecks.slice(0,2):company.experts.filter(e=>!e.isVacant||departedById.has(e.id)).slice(0,2).map(e=>{const departure:any=departedById.get(e.id);return{expertId:e.id,expertName:departure?.expertName||e.name,domains:e.domains.map(s=>s.domain),wasSPOF:departure?.wasSPOF??e.isSPOF,roll:departure?.roll,departed:Boolean(departure),location:e.location==='HQ'?'Corporate HQ':company.sites.find(s=>s.id===e.location)?.name||e.location}});
  const expertCards:RiskCard[]=expertChecks.map((check:any,index:number)=>{const expert=company.experts.find(e=>e.id===check.expertId);const domainLines=expert?.domains.map(s=>`${DOMAIN_INFO[s.domain].label} ${s.score}`)||(check.domains||[]).map((d:KnowledgeDomain)=>DOMAIN_INFO[d]?.label||d);return check.departed?{id:`expert-${check.expertId}-${index}`,kind:'expert-departed',title:`${check.expertName} Resigned!`,location:check.location,domainLines,roll:check.roll,warning:check.wasSPOF?'Single Point of Failure pressure increased the departure risk.':'Standard career transition / relocation.',detail:'A Deep Expert has left the organisation.',impact:'Their uncodified expertise leaves with them. A replacement arrives next round at score 4.',hint:'Build backup expertise and move important know-how out of one person before it walks out the door.',effect:{kind:'expert-departed',expertId:check.expertId}}:{id:`expert-${check.expertId}-${index}`,kind:'expert-retained',title:`${check.expertName} Retained`,location:check.location,domainLines,roll:check.roll,detail:'The expert attrition check did not trigger a departure.',impact:'No expert capability is lost this round.',effect:null};});
  const activeSites=company.sites.filter(s=>!s.isClosed);const siteChecks=Array.isArray(summary.siteChecks)&&summary.siteChecks.length?summary.siteChecks.slice(0,2):activeSites.slice(0,2).map((site,index)=>{const loss=summary.workforceAttrition[index],matching=loss?.siteName===site.name?loss:summary.workforceAttrition.find((e:any)=>e.siteName===site.name);return matching?{siteId:site.id,siteName:site.name,domain:matching.domain,previousScore:matching.previousScore,newScore:matching.newScore,knowledgeLost:true}:{siteId:site.id,siteName:site.name,domain:null,previousScore:null,newScore:null,knowledgeLost:false}});
  const officeCards:RiskCard[]=siteChecks.map((check:any,index:number)=>{const label=check.domain?DOMAIN_INFO[check.domain as KnowledgeDomain]?.label||String(check.domain):null;return check.knowledgeLost?{id:`office-${check.siteId}-${index}`,kind:'workforce-loss',title:`${check.siteName} Workforce Knowledge Loss`,location:check.siteName,domainLines:label?[label]:undefined,detail:`Routine turnover reduced local ${label||'team'} capability.`,detailDomain:label||undefined,impact:`Team Capability ${check.previousScore} → ${check.newScore}.`,hint:'Codified knowledge is not lost when staff leave.',effect:{kind:'workforce-loss',siteId:check.siteId,domain:check.domain as KnowledgeDomain,previousScore:check.previousScore,newScore:check.newScore}}:{id:`office-${check.siteId}-${index}`,kind:'workforce-stable',title:`${check.siteName} Workforce Knowledge Stable`,location:check.siteName,detail:'No vulnerable team knowledge was lost in this check.',impact:'Site Team Capability remains unchanged.',effect:null};});
  return[...expertCards,...officeCards].slice(0,4);
 },[company.experts,company.sites,summary.departedExperts,summary.expertChecks,summary.siteChecks,summary.workforceAttrition]);
 useEffect(()=>{setCurrentIndex(0);setReplacementEffect(null)},[session.round,company.id]);
 const card=cards[Math.min(currentIndex,Math.max(0,cards.length-1))];if(!card)return null;
 const isFinal=currentIndex>=cards.length-1,negative=card.kind==='expert-departed'||card.kind==='workforce-loss',Icon=card.kind==='expert-departed'?UserX:card.kind==='expert-retained'?UserCheck:card.kind==='workforce-loss'?Users:CheckCircle2;
 const departed=(summary.departedExperts||[]).filter((d:any)=>company.experts.some(e=>e.id===d.expertId&&e.isVacant));
 const allPlaced=departed.every((d:any)=>Boolean(placements[d.expertId]));
 const placeReplacement=async(expertId:string,siteId:string)=>{if(!siteId||placing)return;setPlacing(expertId);setPlacementError('');try{const r=await fetch(`/api/sessions/${session.id}/replacement-location`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId:company.id,expertId,siteId})}),data=await r.json();if(!r.ok)throw new Error(data.error||data.message||'Could not set replacement base.');localStorage.setItem(placementKey(expertId),siteId);setPlacements(p=>({...p,[expertId]:siteId}));setReplacementEffect({kind:'replacement',expertId,siteId});onSessionUpdate?.(data.session);}catch(e:any){setPlacementError(e.message||'Could not set replacement base.')}finally{setPlacing(null)}};
 const next=()=>{if(isFinal){if(!allPlaced)return;onAdvanceToNextRound()}else{setReplacementEffect(null);setCurrentIndex(v=>Math.min(v+1,cards.length-1))}};
 const renderDetail=()=>{if(!card.detailDomain||!card.detail.includes(card.detailDomain))return card.detail;const[before,after]=card.detail.split(card.detailDomain);return<>{before}<strong className="font-black text-white">{card.detailDomain}</strong>{after}</>};
 const riverEffect=replacementEffect||card.effect;
 return <div className="w-full min-h-[560px] flex items-start justify-center pt-3 px-3"><div className="w-full max-w-5xl space-y-3">
  <div className={`w-full rounded-2xl border-2 shadow-2xl overflow-hidden ${negative?'border-rose-700 bg-slate-950':'border-emerald-800 bg-slate-950'}`}>
   <div className="px-5 py-3 border-b border-slate-800 bg-slate-900/95 flex items-center justify-between gap-4"><div className="flex items-center gap-2"><ShieldAlert className="w-5 h-5 text-indigo-300"/><div><div className="text-xs uppercase tracking-[0.18em] text-slate-500 font-black">Knowledge Risk</div><div className="text-base font-black text-white">{currentIndex<2?'Expert risk':'City office risk'} · test {currentIndex+1} of {cards.length}</div></div></div><div className="flex items-center gap-1.5">{cards.map((item,index)=><span key={item.id} className={`w-2.5 h-2.5 rounded-full ${index<currentIndex?'bg-emerald-500':index===currentIndex?'bg-indigo-400 ring-2 ring-indigo-300/30':'bg-slate-700'}`}/>)}</div></div>
   <div className="p-5 space-y-4"><div className="flex items-start justify-between gap-5"><div className="flex gap-4 min-w-0"><div className={`shrink-0 w-12 h-12 rounded-xl grid place-items-center border ${negative?'bg-rose-950/70 border-rose-700 text-rose-300':'bg-emerald-950/60 border-emerald-700 text-emerald-300'}`}><Icon className="w-6 h-6"/></div><div className="min-w-0"><h2 className={`text-2xl font-black leading-tight ${negative?'text-rose-300':'text-emerald-300'}`}>{card.title}</h2>{card.location&&<div className="text-sm text-slate-400 mt-1">{card.location}</div>}{card.domainLines?.length?<div className="flex flex-wrap gap-2 mt-2">{card.domainLines.map(line=><span key={line} className="rounded-full bg-slate-900 border border-slate-700 px-2.5 py-1 text-xs font-bold text-slate-300">{line}</span>)}</div>:null}</div></div>{card.roll!=null&&<div className="rounded-xl bg-slate-900 border border-slate-700 px-3 py-2 text-right shrink-0"><div className="text-[10px] uppercase tracking-widest text-slate-500 font-black">Roll</div><div className="text-2xl font-black text-white">{card.roll}</div></div>}</div>
    {card.warning&&<div className="rounded-xl border border-amber-800 bg-amber-950/35 px-4 py-2.5 flex items-start gap-2 text-sm text-amber-100"><AlertTriangle className="w-4 h-4 text-amber-400 mt-0.5 shrink-0"/><span>{card.warning}</span></div>}
    <div className="rounded-xl border border-slate-800 bg-slate-900/70 px-4 py-3"><div className="text-sm text-slate-300">{renderDetail()}</div><div className="mt-2 pt-2 border-t border-slate-800 text-sm"><span className="font-black text-white">Impact: </span><span className="text-slate-400">{card.impact}</span></div></div>
    {card.hint&&<div className="rounded-xl border border-indigo-700 bg-indigo-950/35 px-4 py-2.5 flex items-start gap-3 text-sm text-indigo-100"><Lightbulb className="w-4 h-4 text-amber-300 mt-0.5 shrink-0"/><div><span className="font-black text-white">Reduce the risk: </span>{card.hint}</div></div>}
    {isFinal&&departed.length>0&&<div className="rounded-xl border border-emerald-800 bg-emerald-950/20 p-3"><div className="text-xs uppercase tracking-wider text-emerald-300 font-black">Replacement expert · arrives next round</div><div className="mt-2 grid md:grid-cols-2 gap-2">{departed.map((d:any)=>{const saved=placements[d.expertId],expert=company.experts.find(e=>e.id===d.expertId);return <div key={d.expertId} className="rounded-lg border border-slate-700 bg-slate-950 p-2"><div className="text-sm font-black text-white">{d.expertName}</div><div className="mt-1 flex gap-2"><select defaultValue={saved||''} id={`base-${d.expertId}`} className="min-w-0 flex-1 rounded-lg border border-slate-700 bg-slate-900 px-2 py-1.5 text-xs text-white"><option value="" disabled>Choose city</option>{company.sites.filter(s=>!s.isClosed).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button disabled={Boolean(saved)||placing===d.expertId} onClick={()=>{const el=document.getElementById(`base-${d.expertId}`)as HTMLSelectElement|null;void placeReplacement(d.expertId,el?.value||'')}} className="rounded-lg bg-emerald-500 px-3 text-xs font-black text-slate-950 disabled:bg-slate-800 disabled:text-slate-500">{saved?'BASED':placing===d.expertId?'…':'SET'}</button></div>{saved&&<div className="mt-1 text-[10px] text-emerald-300">Score 4 replacement will start in {company.sites.find(s=>s.id===saved)?.name}.</div>}{expert?.domains?.length?<div className="mt-1 text-[10px] text-slate-500">{expert.domains.map(s=>DOMAIN_INFO[s.domain].label).join(' · ')}</div>:null}</div>})}</div>{placementError&&<div className="mt-2 text-xs text-rose-300">{placementError}</div>}</div>}
    {isFinal&&summary.closedSites.length>0&&<div className="rounded-xl border border-rose-700 bg-rose-950/40 p-3 text-sm text-rose-200"><b className="text-rose-300">Site insolvency:</b> {summary.closedSites.join(', ')}.</div>}
    <div className="flex items-center justify-end pt-1"><button onClick={next} disabled={isFinal&&!allPlaced} className={`shrink-0 rounded-xl px-5 py-3 font-black flex items-center gap-2 transition active:scale-95 disabled:bg-slate-800 disabled:text-slate-500 ${isFinal?'bg-indigo-500 hover:bg-indigo-400 text-white':'bg-white hover:bg-slate-100 text-slate-950'}`}>{isFinal?(session.round>=session.config.rounds?'FINAL DISRUPTION':departed.length&&!allPlaced?'BASE REPLACEMENT FIRST':'NEXT ROUND'):'NEXT'}<ArrowRight className="w-4 h-4"/></button></div>
   </div>
  </div>
  <RiskRiverDiagram company={company} mode={session.experienceMode} effect={riverEffect}/>
 </div></div>;
};
