import React,{useEffect,useState}from'react';
import{Building2,MapPin,Users}from'lucide-react';
import type{ActiveEventV2,CompanyV2,GameSessionV2}from'../types/gameV2.ts';
import{calculateUsableIntranetV2}from'../engine/coreV2.ts';
import{localCodifiedVisible}from'../engine/learningCurveBalanceV1.ts';
import{KnowledgeHubPanel}from'./KnowledgeHubPanel.tsx';
import{DomainBadge,domainsForMode}from'./DomainBadge.tsx';
import{formatCurrency}from'../utils/format.ts';
interface Props{session:GameSessionV2;company:CompanyV2;selectedSiteId:string;isHQSelected:boolean;currentEvent?:ActiveEventV2;onSelectSite:(id:string)=>void;onSelectHQ:()=>void;}
export const BoardSidePanelV2:React.FC<Props>=({session,company,selectedSiteId,isHQSelected,onSelectSite,onSelectHQ})=>{
 const[showTeamMembers,setShowTeamMembers]=useState(false);
 const selectedSite=company.sites.find(site=>site.id===selectedSiteId)||company.sites[0];
 const teamMembers=(session.participants||[]).filter(p=>p.role==='participant'&&p.companyId===company.id);
 const domains=domainsForMode(session.experienceMode);
 const showLocalCodified=localCodifiedVisible(session.experienceMode);
 useEffect(()=>{if(!showTeamMembers)return;const close=()=>setShowTeamMembers(false);document.addEventListener('click',close,{once:true});return()=>document.removeEventListener('click',close)},[showTeamMembers]);
 const changeContext=(value:string)=>value==='HQ'?onSelectHQ():onSelectSite(value);
 return <aside className="rounded-3xl border border-slate-800 bg-slate-900/75 p-4 min-h-[620px] overflow-hidden" aria-label="Company knowledge">
  <div className="relative mb-3"><button onClick={e=>{e.stopPropagation();setShowTeamMembers(v=>!v)}} aria-expanded={showTeamMembers} aria-haspopup="true" className="w-full rounded-xl border border-indigo-700 bg-indigo-950/55 px-3 py-2 text-left font-black text-indigo-100 hover:bg-indigo-950/80 flex items-center justify-between gap-3"><span className="flex items-center gap-2"><Users className="w-4 h-4 text-indigo-300"/>Team Members ({teamMembers.length})</span><span className="text-xs font-black text-indigo-300 uppercase tracking-wider">{showTeamMembers?'Hide':'Show'}</span></button>{showTeamMembers&&<div className="absolute left-0 right-0 top-full mt-1 z-40 rounded-xl border border-indigo-600 bg-slate-950 shadow-2xl overflow-hidden">{teamMembers.length?teamMembers.map(m=><div key={m.id} className="px-3 py-2 text-sm font-bold text-white border-b border-slate-800 last:border-b-0">{m.name}</div>):<div className="px-3 py-2 text-sm text-slate-400">No players assigned.</div>}</div>}</div>
  <div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="text-xs uppercase tracking-widest text-indigo-300 font-black">Selected site</div><div className="mt-2 flex items-center gap-2">{isHQSelected?<Building2 className="w-5 h-5 text-indigo-400"/>:<MapPin className="w-5 h-5 text-indigo-400"/>}<select value={isHQSelected?'HQ':selectedSite.id} onChange={e=>changeContext(e.target.value)} className="min-w-0 flex-1 bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-lg font-black text-white"><option value="HQ">Corporate HQ</option>{company.sites.filter(s=>!s.isClosed).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div></div><div className="text-right shrink-0"><div className="text-xs text-slate-500">Turnover</div><div className="font-black text-white">{isHQSelected?formatCurrency(company.turnover):formatCurrency(selectedSite.turnover)}</div></div></div>
  <div className="mt-4">{isHQSelected?<KnowledgeHubPanel company={company} embedded experienceMode={session.experienceMode}/>:<div className="space-y-2">{domains.map(domain=>{const usableIntranet=calculateUsableIntranetV2(company,selectedSite,domain,session.config);const usable=showLocalCodified?Math.max(selectedSite.teamCapability[domain],selectedSite.codifiedKnowledge[domain],usableIntranet):Math.max(selectedSite.teamCapability[domain],usableIntranet);return <div key={domain} className="rounded-xl bg-slate-950/80 border border-slate-800 px-3 py-3"><div className="flex items-center gap-4"><DomainBadge domain={domain}/><div className="ml-2 flex min-w-0 flex-1 items-center gap-5 text-[13px] font-bold text-slate-300"><span className="whitespace-nowrap">Team <b className="ml-1 text-base font-black text-white">{selectedSite.teamCapability[domain]}</b></span>{showLocalCodified&&<span className="whitespace-nowrap">Docs <b className="ml-1 text-base font-black text-white">{selectedSite.codifiedKnowledge[domain]}</b></span>}<span className="whitespace-nowrap">Corp <b className="ml-1 text-base font-black text-white">{company.intranet[domain]}</b></span></div><span className="ml-auto whitespace-nowrap text-xs font-bold text-slate-500">usable <b className="text-slate-300">{usable}</b></span></div></div>})}</div>}</div>
 </aside>;
};
