import React, { useEffect, useState } from 'react';
import { AlertTriangle, Building2, MapPin, Users, X } from 'lucide-react';
import type { KnowledgeDomain } from '../types/game.ts';
import { DOMAIN_INFO } from '../types/game.ts';
import type { ActiveEventAllocationV2, ActiveEventV2, CompanyV2, GameSessionV2 } from '../types/gameV2.ts';
import { calculateUsableIntranetV2 } from '../engine/coreV2.ts';
import { KnowledgeHubPanel } from './KnowledgeHubPanel.tsx';
import { formatCurrency } from '../utils/format.ts';

interface Props { session:GameSessionV2; company:CompanyV2; selectedSiteId:string; isHQSelected:boolean; currentEvent?:ActiveEventV2; onSelectSite:(id:string)=>void; onSelectHQ:()=>void; }

export const BoardSidePanelV2:React.FC<Props>=({session,company,selectedSiteId,isHQSelected,currentEvent,onSelectSite,onSelectHQ})=>{
 const [showSpofHelp,setShowSpofHelp]=useState(false);
 const [showTeamMembers,setShowTeamMembers]=useState(false);
 const selectedSite=company.sites.find(site=>site.id===selectedSiteId)||company.sites[0];
 const teamMembers=(session.participants||[]).filter(p=>p.role==='participant'&&p.companyId===company.id);
 const committedExpertIds=new Set(currentEvent?(Object.values(currentEvent.allocations) as ActiveEventAllocationV2[]).map(a=>a.expertId).filter((id):id is string=>Boolean(id)):[]);
 useEffect(()=>{if(!showTeamMembers)return;const close=()=>setShowTeamMembers(false);document.addEventListener('click',close,{once:true});return()=>document.removeEventListener('click',close)},[showTeamMembers]);
 const changeContext=(value:string)=>value==='HQ'?onSelectHQ():onSelectSite(value);

 return <>
  <aside className="rounded-3xl border border-slate-800 bg-slate-900/75 p-4 min-h-[620px] overflow-hidden" aria-label="Company knowledge and experts">
   <div className="relative mb-3"><button onClick={e=>{e.stopPropagation();setShowTeamMembers(v=>!v)}} aria-expanded={showTeamMembers} aria-haspopup="true" className="w-full rounded-xl border border-indigo-700 bg-indigo-950/55 px-3 py-2 text-left font-black text-indigo-100 hover:bg-indigo-950/80 flex items-center justify-between gap-3"><span className="flex items-center gap-2"><Users className="w-4 h-4 text-indigo-300" aria-hidden="true"/>Team Members ({teamMembers.length})</span><span className="text-[10px] text-indigo-300 uppercase tracking-wider">{showTeamMembers?'Hide':'Show'}</span></button>{showTeamMembers&&<div className="absolute left-0 right-0 top-full mt-1 z-40 rounded-xl border border-indigo-600 bg-slate-950 shadow-2xl overflow-hidden" role="menu">{teamMembers.length?teamMembers.map(m=><div key={m.id} className="px-3 py-2 text-sm font-bold text-white border-b border-slate-800 last:border-b-0" role="menuitem">{m.name}</div>):<div className="px-3 py-2 text-sm text-slate-400">No players assigned.</div>}</div>}</div>
   <div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="text-xs uppercase tracking-widest text-indigo-300 font-black">Selected site</div><div className="mt-2 flex items-center gap-2">{isHQSelected?<Building2 className="w-5 h-5 text-indigo-400" aria-hidden="true"/>:<MapPin className="w-5 h-5 text-indigo-400" aria-hidden="true"/>}<label className="sr-only" htmlFor="site-context">Company location</label><select id="site-context" value={isHQSelected?'HQ':selectedSite.id} onChange={e=>changeContext(e.target.value)} className="min-w-0 flex-1 bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-lg font-black text-white outline-none focus:border-indigo-400"><option value="HQ">Corporate HQ</option>{company.sites.filter(s=>!s.isClosed).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div></div><div className="text-right shrink-0"><div className="text-xs text-slate-500">Turnover</div><div className="font-black text-white">{isHQSelected?formatCurrency(company.turnover):formatCurrency(selectedSite.turnover)}</div></div></div>
   <div className="mt-4">{isHQSelected?<KnowledgeHubPanel company={company} embedded/>:<div className="space-y-2">{(Object.keys(DOMAIN_INFO) as KnowledgeDomain[]).map(domain=>{const info=DOMAIN_INFO[domain];const usable=calculateUsableIntranetV2(company,selectedSite,domain,session.config);return <div key={domain} className="rounded-xl bg-slate-950/80 border border-slate-800 px-3 py-2"><div className="flex justify-between items-center gap-2"><span className="font-bold text-sm text-white flex items-center gap-2"><span className="w-2.5 h-2.5 rounded-full" style={{backgroundColor:info.color}} aria-hidden="true"/>{info.label}</span><span className="text-xs text-slate-500">usable {Math.max(selectedSite.teamCapability[domain],selectedSite.codifiedKnowledge[domain],usable)}</span></div><div className="grid grid-cols-3 gap-2 mt-1 text-xs text-slate-400"><span>Team <b className="text-white">{selectedSite.teamCapability[domain]}</b></span><span>Docs <b className="text-white">{selectedSite.codifiedKnowledge[domain]}</b></span><span>Corp <b className="text-white">{company.intranet[domain]}</b></span></div></div>})}</div>}</div>
   <div className="mt-5 border-t border-slate-800 pt-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-white font-black text-lg"><Users className="w-5 h-5 text-indigo-400" aria-hidden="true"/>Experts</div><button onClick={()=>setShowSpofHelp(true)} className="rounded-lg border border-amber-500/50 bg-amber-950/35 px-2.5 py-1 text-[11px] font-black text-amber-200 hover:bg-amber-950/60 flex items-center gap-1.5" aria-haspopup="dialog"><AlertTriangle className="w-3.5 h-3.5" aria-hidden="true"/>What is SPOF?</button></div>
    <div className="mt-3 space-y-2">{company.experts.map(expert=>{const siteName=expert.location==='HQ'?'Corporate HQ':company.sites.find(s=>s.id===expert.location)?.name||expert.location;const committed=committedExpertIds.has(expert.id)||['Supporting Event','CoP Participant','Knowledge Transfer','Training','Expertise Capture'].includes(expert.state);const unavailable=expert.isVacant||committed;const spofLabels=expert.spofDomains.map(d=>DOMAIN_INFO[d].label);return <div key={expert.id} className={`rounded-xl border px-3 py-2 ${unavailable?'border-slate-800 bg-slate-950/60 opacity-55':expert.isSPOF?'border-rose-400 bg-amber-400 text-slate-950':'border-amber-300 bg-amber-400 text-slate-950'}`}><div className="flex items-start justify-between gap-3"><div className="font-black">{expert.isVacant?'VACANT':expert.name}</div><div className="font-black italic text-sm text-right">{siteName}</div></div><div className={`text-xs mt-0.5 ${unavailable?'text-slate-400':'text-slate-900'}`}>{expert.domains.map(skill=>`${DOMAIN_INFO[skill.domain].label} ${skill.score}`).join(' · ')||'Replacement pending'}</div>{!expert.isVacant&&expert.isSPOF&&<button onClick={()=>setShowSpofHelp(true)} className="mt-2 rounded-lg border border-rose-700/50 bg-rose-950/90 px-2.5 py-1 text-left text-rose-100 font-black text-[11px]" aria-label={`Single Point of Failure in ${spofLabels.join(', ')}`}><AlertTriangle className="inline w-3.5 h-3.5 mr-1" aria-hidden="true"/>Single Point of Failure - {spofLabels.join(', ')}</button>}{unavailable&&<div className="text-[10px] uppercase tracking-wider font-black text-slate-500 mt-1">{expert.isVacant?'Vacant':committedExpertIds.has(expert.id)?'Committed to current challenge':expert.state}</div>}</div>})}</div>
   </div>
  </aside>
  {showSpofHelp&&<div className="fixed inset-0 z-[160] bg-black/70 backdrop-blur-sm grid place-items-center p-5" onClick={()=>setShowSpofHelp(false)} role="dialog" aria-modal="true" aria-labelledby="spof-title"><div className="w-full max-w-2xl rounded-3xl border-2 border-amber-500 bg-slate-950 shadow-2xl overflow-hidden" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4 border-b border-slate-800 bg-slate-900 px-5 py-4"><div><div className="flex items-center gap-2 text-amber-300 text-xs uppercase tracking-[0.18em] font-black"><AlertTriangle className="w-4 h-4" aria-hidden="true"/>Knowledge Risk</div><h2 id="spof-title" className="text-2xl font-black text-white mt-1">Single Point of Failure</h2></div><button onClick={()=>setShowSpofHelp(false)} aria-label="Close Single Point of Failure explanation" className="rounded-lg border border-slate-700 bg-slate-950 p-2 text-slate-300"><X className="w-5 h-5"/></button></div><div className="p-5 space-y-4 text-sm leading-relaxed"><section className="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><h3 className="font-black text-white">What does it mean?</h3><p className="text-slate-300 mt-1">A Deep Expert is a <b>Single Point of Failure (SPOF)</b> when their expertise is substantially stronger than the knowledge the organisation can access without them. If they are unavailable, the capability gap is exposed.</p></section><section className="rounded-xl border border-rose-800 bg-rose-950/30 p-4"><h3 className="font-black text-rose-200">Why does it matter?</h3><p className="text-slate-300 mt-1">SPOF Experts carry more organisational risk. Pressure increases their departure risk and uncodified expertise can leave with them.</p></section><section className="rounded-xl border border-emerald-800 bg-emerald-950/30 p-4"><h3 className="font-black text-emerald-200">How do I solve it?</h3><p className="text-slate-300 mt-1">Reduce the gap between the Expert and the organisation. Transfer knowledge to teams, codify important know-how, strengthen corporate knowledge and build backup expertise.</p></section></div></div></div>}
 </>;
};
