import React, { useMemo, useState } from 'react';
import { ChevronDown, ChevronRight, Clock, Pause, Play, RotateCcw, Users } from 'lucide-react';
import type { GameEndMode, GameSessionV2 } from '../types/gameV2.ts';
import { formatCurrency } from '../utils/format.ts';

interface Props { session:GameSessionV2; passcode:string; onSessionUpdate:(session:GameSessionV2)=>void; onToast:(message:string)=>void; }

export const FacilitatorControlRoomV2:React.FC<Props>=({session,passcode,onSessionUpdate,onToast})=>{
 const [showPlayers,setShowPlayers]=useState(true);
 const [duration,setDuration]=useState(session.gameDurationMinutes);
 const [maxPlayers,setMaxPlayers]=useState(session.maxPlayersPerCompany);
 const [gameEndMode,setGameEndMode]=useState<GameEndMode>(session.gameEndMode);
 const [finalRoundCount,setFinalRoundCount]=useState(session.finalRoundCount);
 const participants=session.participants||[];
 const players=participants.filter(p=>p.role==='participant');
 const isRunning=Boolean(session.timerEndsAt);
 const estimatedMoves=Math.max(2,Math.floor((duration-session.finalWindowMinutes)/session.minutesPerMove));
 const estimatedRounds=Math.max(1,Math.floor(estimatedMoves/2));
 const roundMode=session.experienceMode==='expert'&&gameEndMode==='rounds';
 const grouped=useMemo(()=>new Map(session.companies.map(c=>[c.id,players.filter(p=>p.companyId===c.id)])),[session.companies,players]);

 const command=async(action:'start'|'pause'|'reset')=>{const r=await fetch(`/api/sessions/${session.id}/timer/${action}`,{method:'POST'});if(r.ok)onSessionUpdate(await r.json())};
 const saveSettings=async()=>{const r=await fetch(`/api/sessions/${session.id}/facilitator/settings`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({passcode,gameDurationMinutes:duration,maxPlayersPerCompany:maxPlayers,gameEndMode:session.experienceMode==='expert'?gameEndMode:'time',finalRoundCount})});const d=await r.json();if(!r.ok){onToast(d.error||'Could not save settings.');return}onSessionUpdate(d.session);onToast('Game settings updated.')};
 const move=async(participantId:string,companyId:string)=>{const r=await fetch(`/api/sessions/${session.id}/facilitator/move-player`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({passcode,participantId,companyId})});const d=await r.json();if(!r.ok){onToast(d.error||'Could not move player.');return}onSessionUpdate(d.session);onToast('Player moved to the new company.')};

 return <div className="space-y-4" aria-label="Facilitator control panel">
  <section className="rounded-2xl border border-indigo-800 bg-indigo-950/25 p-4"><div className="text-[10px] uppercase tracking-wider text-indigo-300 font-black">How to run the room</div><div className="grid md:grid-cols-3 gap-3 mt-2 text-xs text-slate-300 leading-relaxed"><p><b className="text-white">1 · Form teams.</b> Players may choose a company when joining, or leave it blank and the game places them into the smallest team below the player limit.</p><p><b className="text-white">2 · Let teams decide.</b> Each company should discuss its own Challenges and investments. The facilitator watches progress here rather than making choices for them.</p><p><b className="text-white">3 · Manage exceptions.</b> Expand team assignments below to move somebody manually. Timing and player-limit changes affect everyone immediately.</p></div></section>

  <div className="grid lg:grid-cols-[1fr_360px] gap-4">
   <section className="rounded-2xl border border-slate-700 bg-slate-900 p-4">
    <div className="flex items-center justify-between gap-3"><div><div className="text-[10px] uppercase text-slate-500 font-black">Companies</div><h2 className="text-lg font-black text-white">Team management</h2></div><button onClick={()=>setShowPlayers(v=>!v)} aria-expanded={showPlayers} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-xs font-black text-slate-300 flex items-center gap-2">{showPlayers?<ChevronDown className="w-4 h-4"/>:<ChevronRight className="w-4 h-4"/>}{showPlayers?'Hide':'Show'} player assignments</button></div>
    <div className="mt-3 grid md:grid-cols-2 gap-2">{session.companies.map(company=>{const team=grouped.get(company.id)||[];const events=session.activeEvents[company.id]||[];const unresolved=events.filter(e=>!e.isResolved).length;return <div key={company.id} className="rounded-xl border border-slate-700 bg-slate-950 p-3"><div className="flex justify-between gap-3"><div><b className="text-white">{company.name}</b><div className="text-[10px] text-slate-500">{team.length}/{session.maxPlayersPerCompany} players · {unresolved?`${unresolved} task${unresolved===1?'':'s'} open`:'ready'}</div></div><div className="text-right text-xs font-black text-emerald-300">{formatCurrency(company.turnover)}</div></div>{showPlayers&&<div className="mt-2 space-y-1">{team.length?team.map(player=><div key={player.id} className="flex items-center gap-2 rounded-lg border border-slate-800 bg-slate-900 px-2 py-1.5"><Users className="w-3.5 h-3.5 text-indigo-300" aria-hidden="true"/><span className="flex-1 text-xs text-white font-bold truncate">{player.name}</span><label className="sr-only" htmlFor={`move-${player.id}`}>Move {player.name} to company</label><select id={`move-${player.id}`} value={player.companyId} onChange={e=>move(player.id,e.target.value)} className="rounded-md border border-slate-700 bg-slate-950 px-1.5 py-1 text-[10px] text-slate-300">{session.companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>):<div className="text-[10px] text-slate-600 italic">No players assigned</div>}</div>}</div>})}</div>
   </section>

   <aside className="space-y-3">
    <section className="rounded-2xl border border-slate-700 bg-slate-900 p-4"><div className="flex items-center gap-2"><Clock className="w-4 h-4 text-indigo-300"/><h3 className="font-black text-white">Game timing</h3></div>{session.experienceMode==='expert'&&<label className="block mt-3 text-[10px] uppercase text-slate-500 font-black">End game by<select value={gameEndMode} onChange={e=>setGameEndMode(e.target.value as GameEndMode)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-sm text-white normal-case"><option value="time">Time</option><option value="rounds">Round count</option></select></label>}<div className="grid grid-cols-2 gap-2 mt-3">{roundMode?<label className="text-[10px] uppercase text-slate-500 font-black">Normal rounds<input type="number" min={1} max={200} value={finalRoundCount} onChange={e=>setFinalRoundCount(Math.max(1,Math.min(200,Number(e.target.value))))} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-sm text-white normal-case"/></label>:<label className="text-[10px] uppercase text-slate-500 font-black">Length (min)<input type="number" min={20} max={240} step={5} value={duration} onChange={e=>setDuration(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-sm text-white normal-case"/></label>}<label className="text-[10px] uppercase text-slate-500 font-black">Max/team<input type="number" min={1} max={20} value={maxPlayers} onChange={e=>setMaxPlayers(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-sm text-white normal-case"/></label></div><button onClick={saveSettings} className="mt-2 w-full rounded-lg bg-indigo-600 py-2 text-xs font-black text-white">Save settings</button>{!roundMode&&<div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>command(isRunning?'pause':'start')} className="rounded-lg border border-emerald-700 bg-emerald-950/40 py-2 text-xs font-black text-emerald-200 flex items-center justify-center gap-1">{isRunning?<Pause className="w-3.5 h-3.5"/>:<Play className="w-3.5 h-3.5"/>}{isRunning?'Pause':'Start'}</button><button onClick={()=>command('reset')} className="rounded-lg border border-slate-700 bg-slate-950 py-2 text-xs font-black text-slate-300 flex items-center justify-center gap-1"><RotateCcw className="w-3.5 h-3.5"/>Reset</button></div>}<p className="mt-3 text-[10px] text-slate-500 leading-relaxed">{roundMode?`The final Challenge begins after Round ${finalRoundCount} is completed. The timer is not used to end this Expert game.`:`At ${duration} minutes, planning assumes about ${estimatedMoves} normal Challenge moves (~${estimatedRounds} rounds) before the last ${session.finalWindowMinutes}-minute climactic window. The final Challenge is time-triggered only; if the timer has never been started, it cannot start automatically.`}</p></section>
    <section className="rounded-2xl border border-slate-700 bg-slate-900 p-4"><div className="text-[10px] uppercase text-slate-500 font-black">Experience mode</div><div className="text-lg font-black text-white capitalize mt-1">{session.experienceMode}</div><p className="text-[10px] text-slate-500 mt-1">{session.experienceMode==='newbie'?'Capabilities are introduced progressively over Rounds 1–3.':'All capabilities and Charts are available from Round 1.'}</p></section>
   </aside>
  </div>
 </div>;
};
