export interface KMManualSection{title:string;game:string;real:string;source:string;}

export const KM_MANUAL_INTRO=`Knowledge Management is not about doing knowledge work - everyone does that. It is about managing the infrastructure that maximises the impact of knowledge across the organisation. KM makes expertise visible, protects what is critical and vulnerable, improves how knowledge moves, and turns knowledge into organisational capability through people, reusable content and automation.`;

export const KM_MANUAL_SECTIONS:KMManualSection[]=[
 {title:'Knowledge domains',game:'Engineering, Human Resources, Marketing and Operations are simplified bodies of business knowledge. Finance is also visible in Expert mode. Most real decisions combine several domains; the categories simply make otherwise invisible capability visible enough to manage.',real:'ISO 30401 treats organisational knowledge as existing within and between people, teams and organisations, in human, codified and embedded forms. The game domains are a practical visual shorthand, not organisational silos.',source:'ISO 30401 / ISO DIS 30401 - https://www.iso.org/standard/89436.html'},
 {title:'Event cards',game:'Events are business problems and opportunities. Local Events affect one site; enterprise Events affect the whole organisation. As the simulation develops, stakes and knowledge requirements increase.',real:'OECD guidance distinguishes information from knowledge by the ability to understand and use information for a purpose. Knowledge therefore creates value only when it can be applied where the work or decision occurs.',source:'OECD Oslo Manual 2018 - https://www.oecd.org/en/publications/oslo-manual-2018_9789264304604-en/full-report/component-7.html'},
 {title:'Knowledge Suite',game:'The Knowledge Suite shows what the team can actually use for the current Event: local Team Capability, corporate knowledge through the Corporate Intranet, and in Expert mode local codified knowledge. The question is not what the company knows somewhere, but what this decision can reach now.',real:'APQC defines KM as structured processes that help information and knowledge flow to the right people at the right time so they can find, understand, share and use it to create value.',source:'APQC, What Is Knowledge Management? - https://www.apqc.org/expertise/whatisknowledgemanagement'},
 {title:'Experts and SPOF risk',game:'Experts provide deep specialist capability. They are scarce, can be committed elsewhere and may leave. A Single Point of Failure (SPOF) appears when too much critical knowledge depends on one person.',real:'Expertise location connects people to knowledgeable colleagues. Structured knowledge transfer reduces the risk of valuable tacit knowledge disappearing when experienced people move or retire.',source:'APQC Expertise Location and Structured Knowledge Transfer - https://www.apqc.org/resource-library/resource/understanding-expertise-location-0'},
 {title:'Knowledge Transfer',game:'Move useful knowledge directly from a stronger site to a weaker site. It improves the receiving site rather than merely solving one Event.',real:'Effective knowledge transfer closes a knowledge gap by getting knowledge back into organisational work so it can be applied and reused.',source:'APQC, What is Knowledge Transfer? - https://www.apqc.org/blog/what-knowledge-transfer'},
 {title:'Local Training',game:'Use deep expertise to raise local Team Capability. It reduces dependence on an individual expert and makes future decisions more resilient.',real:'Structured transfer and on-the-job learning are used to convert individual know-how into capability in other people and teams.',source:'APQC, Understanding Structured Knowledge Transfer - https://www.apqc.org/resource-library/resource/understanding-structured-knowledge-transfer-0/html'},
 {title:'Corporate knowledge and automation',game:'Updating the Corporate Intranet makes useful knowledge reusable across sites. Automation embeds stable, repeatable knowledge into systems so performance is less dependent on human recall or availability.',real:'ISO 30401 recognises knowledge in people, codified knowledge and embedded knowledge. KM therefore includes both human knowledge processes and the systems/workflows into which useful knowledge is intentionally embedded.',source:'ISO DIS 30401 - https://www.iso.org/standard/89436.html'},
 {title:'Communities and external knowledge',game:'Communities of Practice let teams draw on peer knowledge beyond their local site. External expertise buys knowledge the organisation does not currently possess.',real:'APQC describes CoPs as networks that transfer practices and lessons, provide access to expertise and support learning. OECD also recognises that organisations acquire useful knowledge externally.',source:'APQC Communities of Practice - https://www.apqc.org/expertise/knowledge-management/communities-of-practice'},
 {title:'Horizon Scan',game:'Horizon scanning gives earlier visibility of uncertainty. It can reveal what may be coming and, when conditions allow, delay a known Event so the organisation can prepare.',real:'KM supports organisational context-sensing, learning, risk mitigation and opportunity exploitation. Foresight is valuable when it changes what knowledge or capability the organisation builds before the event arrives.',source:'ISO DIS 30401 - https://www.iso.org/standard/89436.html'},
 {title:'Reputation',game:'Reputation represents social capital: relationships and credibility accumulated over time that can sometimes secure help when normal knowledge mechanisms are insufficient.',real:'Knowledge often moves through trusted relationships as well as formal repositories. Communities and professional networks create the relational infrastructure through which expertise can be found and shared.',source:'APQC Communities of Practice - https://www.apqc.org/expertise/knowledge-management/communities-of-practice'},
 {title:'The River Diagram',game:'The River is the main diagnostic picture. White dots are site capability; yellow people are experts. The upper and lower boundaries show the strongest and weakest sites. The space between them is the transfer gap: knowledge that exists somewhere but has not reached every place that may need it. Read the shape, not just the average. A low isolated dot suggests a transfer target. A yellow expert far above the sites suggests vulnerability. A flatter, higher River usually means more distributed and resilient capability.',real:'APQC maps knowledge as a flow from creation and identification through collection, review, sharing, access and use. Mapping where knowledge sits and where flow breaks down exposes bottlenecks. ISO 30401 similarly prioritises critical and vulnerable knowledge.',source:'APQC Knowledge Flow Process - https://www.apqc.org/resource-library/resource-listing/apqcs-knowledge-flow-process-framework'},
 {title:'Knowledge Risk',game:'Knowledge Risk tests whether capability survives normal organisational change. People resign and teams lose experience. Transfer, training, reusable knowledge and automation should make the River more resilient before losses occur.',real:'ISO 30401 explicitly prioritises critical and vulnerable knowledge. Structured knowledge transfer is a common response when important know-how is concentrated in people who may leave.',source:'ISO DIS 30401 - https://www.iso.org/standard/89436.html'},
 {title:'After Action Review',game:'The AAR compares what you intended with what happened, explores why it differed and identifies what should change. Benchmark charts and mini-Rivers are evidence for reflection, not just a leaderboard.',real:'Debriefs and AARs surface experience and feed learning back into future work. Their value comes from changed practice and decisions, not simply documenting the discussion.',source:'APQC, What is Knowledge Transfer? - https://www.apqc.org/blog/what-knowledge-transfer'},
 {title:'Determining the value of KM work',game:'Start with the business exposure or opportunity, identify the knowledge mechanism causing the performance gap, choose an intervention, measure what changed in the work, translate that change into business value, then compare it with the cost of the KM intervention.',real:'APQC recommends linking KM participation and process changes to business outcomes such as cycle time, cost, retention and revenue rather than relying on activity counts. OECD also treats knowledge-based capital as an intangible asset capable of generating future benefits.',source:'APQC KM Measurement - https://www.apqc.org/resource-library/resource/understanding-knowledge-management-measurement-0/html'}
];

const ascii=(text:string)=>text.replace(/[–—]/g,'-').replace(/[“”]/g,'"').replace(/[’]/g,"'").replace(/[^\x20-\x7E]/g,'');
const wrap=(text:string,width=88)=>{const words=ascii(text).split(/\s+/);const lines:string[]=[];let line='';for(const word of words){if(!word)continue;const next=line?`${line} ${word}`:word;if(next.length>width&&line){lines.push(line);line=word}else line=next}if(line)lines.push(line);return lines;};
const esc=(text:string)=>text.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');

export function downloadKMManualPdf(){
 const pages:string[][]=[];let current:string[]=[];
 const add=(line='')=>{if(current.length>=54){pages.push(current);current=[]}current.push(line)};
 add('THE PERFORMANCE GAP - KNOWLEDGE MANAGEMENT MANUAL');add('DeltaKnowledge | Stuart French | www.DeltaKnowledge.net');add('');wrap(KM_MANUAL_INTRO).forEach(add);add('');
 KM_MANUAL_SECTIONS.forEach((section,index)=>{if(current.length>43){pages.push(current);current=[]}add(`${index+1}. ${section.title.toUpperCase()}`);wrap(`GAME: ${section.game}`).forEach(add);add('');wrap(`REAL WORLD: ${section.real}`).forEach(add);wrap(`SOURCE: ${section.source}`).forEach(add);add('')});
 if(current.length)pages.push(current);
 const objects:string[]=[];const addObj=(body:string)=>{objects.push(body);return objects.length};
 const font=addObj('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
 const pageIds:number[]=[];
 const contentIds:number[]=[];
 for(const lines of pages){const commands=['BT','/F1 9 Tf','44 800 Td','12 TL',...lines.flatMap((line,i)=>[`${i?'T* ':''}(${esc(line)}) Tj`]),'ET'].join('\n');contentIds.push(addObj(`<< /Length ${commands.length} >>\nstream\n${commands}\nendstream`));pageIds.push(0)}
 const pagesId=objects.length+pages.length+1;
 for(let i=0;i<pages.length;i++)pageIds[i]=addObj(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`);
 addObj(`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`);
 const catalog=addObj(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);
 let pdf='%PDF-1.4\n';const offsets=[0];objects.forEach((body,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${body}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offsets.length;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;
 const blob=new Blob([pdf],{type:'application/pdf'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='The_Performance_Gap_KM_Manual.pdf';document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);
}
