import React from 'react';
import { Download, X } from 'lucide-react';
import { downloadKMManualPdf, KM_MANUAL_INTRO, KM_MANUAL_SECTIONS } from './kmManualContent.ts';

interface Props { onClose:()=>void; }

export const KMManualOverlay:React.FC<Props>=({onClose})=><div className="fixed inset-0 z-[240] bg-black/75 p-3 sm:p-5 grid place-items-center" role="dialog" aria-modal="true" aria-label="Knowledge Management Manual">
 <div className="w-full max-w-5xl h-[min(90dvh,900px)] rounded-3xl border-2 border-violet-500 bg-[#0b0f18] shadow-2xl overflow-hidden flex flex-col">
  <header className="shrink-0 border-b border-slate-800 px-5 py-4 flex items-center gap-3"><div className="min-w-0"><div className="text-[10px] uppercase tracking-[.18em] text-emerald-300 font-black">The Performance Gap</div><h2 className="text-xl font-black text-white">Knowledge Management Manual</h2></div><button onClick={downloadKMManualPdf} className="ml-auto rounded-xl border border-emerald-700 bg-emerald-950/35 px-3 py-2 text-xs font-black text-emerald-200 flex items-center gap-2"><Download className="w-4 h-4"/>Download PDF</button><button onClick={onClose} className="w-10 h-10 grid place-items-center rounded-xl border border-slate-700" aria-label="Close manual"><X className="w-5 h-5"/></button></header>
  <div className="min-h-0 overflow-y-auto p-5"><div className="rounded-2xl border border-violet-800 bg-violet-950/25 p-4 text-sm leading-relaxed text-violet-100 font-semibold">{KM_MANUAL_INTRO}</div><div className="mt-4 grid lg:grid-cols-2 gap-3">{KM_MANUAL_SECTIONS.map((section,index)=><section key={section.title} className={`rounded-2xl border p-4 ${section.title==='The River Diagram'?'lg:col-span-2 border-emerald-600 bg-emerald-950/20':'border-slate-700 bg-slate-950/70'}`}><div className="text-[10px] uppercase tracking-wider text-slate-500 font-black">{index+1}</div><h3 className="text-base font-black text-white">{section.title}</h3><div className="mt-2 text-[10px] uppercase text-violet-300 font-black">In the game</div><p className="mt-1 text-sm leading-relaxed text-slate-200">{section.game}</p><div className="mt-3 text-[10px] uppercase text-emerald-300 font-black">In the real world</div><p className="mt-1 text-sm leading-relaxed text-slate-400">{section.real}</p><div className="mt-2 text-[10px] text-slate-600 break-all">{section.source}</div></section>)}</div><div className="mt-5 text-xs leading-relaxed text-slate-500">Prepared for The Performance Gap by Stuart French, DeltaKnowledge. This is an introductory guide; the cited standards and research remain the authoritative sources.</div></div>
 </div>
</div>;
