import React, { useEffect, useMemo, useState } from 'react';
import { X } from 'lucide-react';
import type { GamePhase, KnowledgeDomain } from '../types/game.ts';
import { DOMAIN_INFO } from '../types/game.ts';
import type { CompanyV2, ExperienceMode } from '../types/gameV2.ts';
import { riverSiteKnowledgeScore, riverTransferTarget } from '../engine/riverKnowledgeV1.ts';
import { formatCurrency } from '../utils/format.ts';

interface Props { company: CompanyV2; mode:ExperienceMode; phase:GamePhase; totalActions?:number; onClose: () => void; onShare:(sourceSiteId:string,targetSiteId:string,domain:KnowledgeDomain)=>Promise<{success:boolean;message?:string}>; }
const NEWBIE_DOMAINS: KnowledgeDomain[] = ['engineering','hr','marketing','operations'];
const EXPERT_DOMAINS: KnowledgeDomain[] = [...NEWBIE_DOMAINS,'finance'];
const ABBR: Record<string,string> = { melbourne:'MEL',sydney:'SYD',brisbane:'BNE',adelaide:'ADL',perth:'PER',darwin:'DRW',HQ:'HQ' };
const TRANSFER_COST=5;
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase();

type Lens={x:number;y:number}|null;

export const RiverDiagramOverlay:React.FC<Props>=({company,mode,phase,totalActions=5,onClose,onShare})=>{
 const sites=company.sites.filter(s=>!s.isClosed);
 const experts=company.experts.filter(e=>!e.isVacant);
 const domains=mode==='expert'?EXPERT_DOMAINS:NEWBIE_DOMAINS;
 const [domain,setDomain]=useState<KnowledgeDomain>('engineering');
 const [sourceSiteId,setSourceSiteId]=useState('');
 const [targetSiteId,setTargetSiteId]=useState('');
 const [busy,setBusy]=useState(false);
 const [message,setMessage]=useState('');
 const [lens,setLens]=useState<Lens>(null);
 useEffect(()=>{if(!domains.includes(domain))setDomain(domains[0])},[mode,domain]);
 const data=useMemo(()=>domains.map(d=>{const scores=sites.map(site=>({site,score:riverSiteKnowledgeScore(site,d,mode)}));return {domain:d,scores,south:Math.min(...scores.map(x=>x.score)),north:Math.max(...scores.map(x=>x.score))};}),[company,mode]);
 const expertMarks=useMemo(()=>experts.flatMap(expert=>expert.domains.filter(skill=>domains.includes(skill.domain)).map(skill=>({expert,domain:skill.domain,score:skill.score}))),[company,mode]);
 const selectedData=data.find(d=>d.domain===domain)||data[0];
 useEffect(()=>{if(!selectedData?.scores.length)return;const sorted=[...selectedData.scores].sort((a,b)=>b.score-a.score);setSourceSiteId(current=>selectedData.scores.some(x=>x.site.id===current)?current:sorted[0].site.id);setTargetSiteId(current=>selectedData.scores.some(x=>x.site.id===current)?current:sorted[sorted.length-1].site.id)},[domain,company,mode]);
 const source=sites.find(s=>s.id===sourceSiteId),target=sites.find(s=>s.id===targetSiteId);
 const sourceScore=source?riverSiteKnowledgeScore(source,domain,mode):0,currentTarget=target?.teamCapability[domain]||0,transferTarget=riverTransferTarget(sourceScore),canBenefit=Boolean(source&&target&&source.id!==target.id&&transferTarget>currentTarget);
 const maxY=Math.max(6,...data.flatMap(d=>d.scores.map(x=>x.score)),...expertMarks.map(x=>x.score));
 const W=920,H=330,padL=62,padR=32,padT=28,padB=54,x=(i:number)=>domains.length===1?(padL+(W-padR))/2:padL+i*((W-padL-padR)/(domains.length-1)),y=(v:number)=>padT+(maxY-v)*((H-padT-padB)/maxY);
 const northPath=data.map((d,i)=>`${i?'L':'M'} ${x(i)} ${y(d.north)}`).join(' '),southPath=data.map((d,i)=>`${i?'L':'M'} ${x(i)} ${y(d.south)}`).join(' '),gapFill=`${northPath} ${[...data].reverse().map((d,ri)=>`L ${x(data.length-1-ri)} ${y(d.south)}`).join(' ')} Z`;
 const spreadLabelYs=(preferred:number[],gap=18)=>{if(!preferred.length)return[] as number[];const min=padT+10,max=H-padB-7;const ordered=preferred.map((value,index)=>({value,index})).sort((a,b)=>a.value-b.value);const placed=ordered.map((item,index)=>Math.max(min,index?0:item.value));for(let i=0;i<ordered.length;i++)placed[i]=Math.max(i?placed[i-1]+gap:min,Math.max(min,ordered[i].value));if(placed[placed.length-1]>max){placed[placed.length-1]=max;for(let i=placed.length-2;i>=0;i--)placed[i]=Math.min(placed[i],placed[i+1]-gap);if(placed[0]<min){placed[0]=min;for(let i=1;i<placed.length;i++)placed[i]=Math.max(placed[i],placed[i-1]+gap)}}const result=Array(preferred.length).fill(0);ordered.forEach((item,index)=>{result[item.index]=placed[index]});return result};
 const share=async()=>{if(!canBenefit||phase!=='investment'||busy)return;setBusy(true);setMessage('');try{const result=await onShare(sourceSiteId,targetSiteId,domain);setMessage(result.message||'Knowledge transferred.');}finally{setBusy(false)}};
 const knowledgeExplanation=mode==='newbie'?'Each white dot is that site’s Team Capability in the domain. Yellow expert markers show where your experts sit on the same knowledge scale. The green lines show the weakest and strongest sites. The shaded area is the internal performance gap: knowledge the company already has, but has not yet moved to every place that needs it.':'Each white dot is a site’s strongest locally available knowledge in that domain — Team Capability or Local Codified Knowledge, whichever is higher. Yellow expert markers show expert capability. The green lines show the weakest and strongest sites. The shaded area highlights where internal transfer may close a performance gap before outside expertise is required.';
 const chart=()=> <>
  {[0,1,2,3,4,5,6,7,8].filter(v=>v<=maxY).map(v=><g key={`grid-${v}`}><line x1={padL} y1={y(v)} x2={W-padR} y2={y(v)} stroke="#243047" strokeWidth="1"/><text x={padL-12} y={y(v)+5} textAnchor="end" fill="#94a3b8" fontSize="15">{v}</text></g>)}
  <path d={gapFill} fill="#0c4a6e" fillOpacity="0.78"/><path d={northPath} fill="none" stroke="#22c55e" strokeWidth="4" strokeLinejoin="round"/><path d={southPath} fill="none" stroke="#22c55e" strokeWidth="4" strokeLinejoin="round"/>
  {data.map((d,i)=>{const domainExperts=expertMarks.filter(mark=>mark.domain===d.domain);const labelYs=spreadLabelYs([...d.scores.map(({score})=>y(score)-9),...domainExperts.map(mark=>y(mark.score)-3)]);return <g key={`domain-${d.domain}`}><text x={x(i)} y={H-17} textAnchor="middle" fill="#e2e8f0" fontSize="16" fontWeight="700">{DOMAIN_INFO[d.domain].label}</text>{d.scores.map(({site,score},si)=>{const jitter=(si-(d.scores.length-1)/2)*9;return <g key={`site-${d.domain}-${site.id}`}><circle cx={x(i)+jitter} cy={y(score)} r="5.5" fill="#f8fafc" stroke="#0f172a" strokeWidth="2"/><text x={x(i)+jitter+9} y={labelYs[si]} fill="#f8fafc" fontSize="13" fontWeight="800" paintOrder="stroke" stroke="#0b1020" strokeWidth="3" strokeLinejoin="round">{ABBR[site.id]||site.name.slice(0,3).toUpperCase()}</text></g>})}{domainExperts.map((mark,ei)=>{const jitter=(ei-(domainExperts.length-1)/2)*58,px=x(i)+jitter,py=y(mark.score),loc=ABBR[mark.expert.location]||mark.expert.location.slice(0,3).toUpperCase(),labelY=labelYs[d.scores.length+ei];return <g key={`expert-${mark.expert.id}-${d.domain}`}><circle cx={px} cy={py} r="22" fill="#facc15" stroke="#713f12" strokeWidth="2"/><circle cx={px} cy={py-7} r="5" fill="#374151"/><path d={`M ${px-9} ${py+11} Q ${px-8} ${py-1} ${px} ${py-1} Q ${px+8} ${py-1} ${px+9} ${py+11} Z`} fill="#374151"/><text x={px+28} y={labelY} fill="#fde047" fontSize="13" fontWeight="900" paintOrder="stroke" stroke="#0b1020" strokeWidth="3" strokeLinejoin="round">{initials(mark.expert.name)} · {loc}</text></g>})}</g>})}
  <text x="20" y={H/2} textAnchor="middle" fill="#94a3b8" fontSize="15" transform={`rotate(-90 20 ${H/2})`}>Knowledge level</text>
 </>;
 const moveLens=(event:React.PointerEvent<SVGSVGElement>)=>{const rect=event.currentTarget.getBoundingClientRect();setLens({x:(event.clientX-rect.left)*W/rect.width,y:(event.clientY-rect.top)*H/rect.height})};
 return <div className="fixed inset-0 z-[220] bg-black/75 backdrop-blur-sm p-3 sm:p-4 flex items-center justify-center overflow-hidden" role="dialog" aria-modal="true" aria-label="Knowledge Transfer"><div className="w-full max-w-6xl max-h-[92vh] rounded-3xl border border-slate-600 bg-[#0b1020] shadow-2xl overflow-hidden flex flex-col">
  <div className="shrink-0 flex items-start justify-between gap-4 border-b border-slate-800 bg-[#0b1020]/95 px-5 py-3 backdrop-blur-md"><div><div className="text-sm uppercase tracking-[0.18em] text-emerald-300 font-black">Knowledge Transfer · Internal capability map</div><h2 className="text-2xl font-black text-white">Where does knowledge already exist?</h2><p className="text-base text-slate-300 mt-1 max-w-4xl leading-snug">{knowledgeExplanation}</p></div><div className="flex items-start gap-3"><div className="rounded-xl border border-slate-700 bg-slate-950/80 px-3 py-2"><div className="text-xs uppercase tracking-wider text-slate-400 font-black text-right">Company actions</div><div className="mt-1.5 flex gap-2" aria-label={`${company.actionsRemaining} of ${totalActions} company actions remaining`}>{Array.from({length:totalActions},(_,i)=><span key={i} className={`h-5 w-5 rounded-full border-2 ${i<company.actionsRemaining?'border-amber-200 bg-amber-400 shadow-[0_0_7px_rgba(250,204,21,.55)]':'border-amber-800 bg-amber-950'}`}/>)}</div></div><button onClick={onClose} className="shrink-0 rounded-xl border border-slate-700 bg-slate-900 p-2 text-white hover:border-emerald-400" aria-label="Close Knowledge Transfer"><X className="w-5 h-5"/></button></div></div>
  <div className="min-h-0 overflow-y-auto px-5 pb-4"><div className="mt-3 grid lg:grid-cols-[minmax(0,1fr)_300px] gap-4 items-start"><div className="min-h-0 flex flex-col gap-2"><div className="rounded-2xl border border-slate-700 bg-slate-950 p-2 overflow-hidden"><svg viewBox={`0 0 ${W} ${H}`} className="w-full h-[min(34vh,315px)] min-h-[255px]" role="img" aria-label="Knowledge Transfer map showing site and expert knowledge scores by domain" onPointerMove={moveLens} onPointerLeave={()=>setLens(null)} style={{cursor:'zoom-in'}}><defs><clipPath id="river-lens"><circle cx={lens?.x||0} cy={lens?.y||0} r="78"/></clipPath></defs>{chart()}{lens&&<g pointerEvents="none"><circle cx={lens.x} cy={lens.y} r="78" fill="#020617"/><g clipPath="url(#river-lens)" transform={`translate(${lens.x} ${lens.y}) scale(2) translate(${-lens.x} ${-lens.y})`}>{chart()}</g><circle cx={lens.x} cy={lens.y} r="78" fill="none" stroke="#f8fafc" strokeWidth="2"/></g>}</svg></div><div className="grid md:grid-cols-3 gap-2 text-sm leading-snug"><div className="rounded-xl border border-emerald-800 bg-emerald-950/30 p-2"><b className="text-emerald-300">Strongest site</b><div className="text-slate-300 mt-0.5">Best site-level knowledge. Yellow expert markers show expert knowledge that may sit above it.</div></div><div className="rounded-xl border border-sky-800 bg-sky-950/30 p-2"><b className="text-sky-300">Transfer gap</b><div className="text-slate-300 mt-0.5">Knowledge the company already has but has not yet moved to every place that needs it.</div></div><div className="rounded-xl border border-emerald-800 bg-emerald-950/30 p-2"><b className="text-emerald-300">Weakest site</b><div className="text-slate-300 mt-0.5">The lowest current site score — often the best place to target transfer first.</div></div></div></div>
  <aside className="rounded-2xl border border-emerald-800 bg-emerald-950/20 p-4"><div className="text-sm uppercase tracking-wider text-emerald-300 font-black">Knowledge Transfer</div><h3 className="text-xl font-black text-white mt-1">Move knowledge to where it is needed</h3><p className="text-base text-slate-300 mt-1 leading-snug">Use a stronger site as the teacher. The receiving site can reach about <b>80%</b> of what that teaching site currently knows in the selected domain.</p><label className="block mt-3 text-sm uppercase text-slate-400 font-black">Domain<select value={domain} onChange={e=>setDomain(e.target.value as KnowledgeDomain)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-base text-white normal-case">{domains.map(d=><option key={d} value={d}>{DOMAIN_INFO[d].label}</option>)}</select></label><label className="block mt-2 text-sm uppercase text-slate-400 font-black">Teaching site<select value={sourceSiteId} onChange={e=>setSourceSiteId(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-base text-white normal-case">{[...selectedData.scores].sort((a,b)=>b.score-a.score).map(({site,score})=><option key={site.id} value={site.id}>{site.name} · {score}</option>)}</select></label><label className="block mt-2 text-sm uppercase text-slate-400 font-black">Receiving site<select value={targetSiteId} onChange={e=>setTargetSiteId(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-base text-white normal-case">{[...selectedData.scores].sort((a,b)=>a.score-b.score).map(({site,score})=><option key={site.id} value={site.id}>{site.name} · {score}</option>)}</select></label><div className="mt-2 grid grid-cols-3 gap-1 text-center"><Metric label="Teacher" value={sourceScore}/><Metric label="Team now" value={currentTarget}/><Metric label="After" value={transferTarget}/></div>{phase==='investment'?<button onClick={share} disabled={!canBenefit||busy} className="mt-2 w-full rounded-xl bg-amber-400 py-2.5 font-black text-slate-950 disabled:bg-slate-800 disabled:text-slate-500">{busy?'TRANSFERRING…':`TRANSFER · 1 ACTION · ${formatCurrency(TRANSFER_COST)}`}</button>:<div className="mt-2 rounded-xl border border-slate-700 bg-slate-950 p-2 text-center text-sm text-slate-400">Planning view available now. Execute Knowledge Transfer during the <b className="text-white">Invest</b> phase.</div>}{!canBenefit&&source&&target&&<div className="mt-2 text-sm text-amber-300">Choose a stronger teaching site or a weaker receiving site.</div>}{message&&<div className="mt-2 rounded-lg border border-emerald-800 bg-emerald-950/30 p-2 text-sm text-emerald-200">{message}</div>}</aside></div></div>
 </div></div>;
};
const Metric:React.FC<{label:string;value:number|string}>=({label,value})=><div className="rounded-lg border border-emerald-900 bg-slate-950 p-2"><div className="text-xs uppercase text-slate-400 font-black">{label}</div><div className="text-xl font-black text-white">{value}</div></div>;
