import { mkdirSync, writeFileSync } from 'node:fs';
import { DEFAULT_CONFIG } from '../src/engine/config.ts';
import { defaultActionsForMode, expertCurveLabel, expertCurveModifier, localCodifiedVisible } from '../src/engine/learningCurveBalanceV1.ts';
import type { BusinessStrategy, ExperienceMode, KnowledgeStrategy } from '../src/types/gameV2.ts';
import type { EventCard, KnowledgeDomain } from '../src/types/game.ts';

type Mode=ExperienceMode;
type Domain=KnowledgeDomain;
type Intervention='river'|'intranet'|'expert_deploy'|'expert_coach'|'expert_capture'|'cop'|'training'|'automation'|'aar'|'external';
type RiskPosture='bullish'|'balanced'|'risk_averse';
const DOMAINS:Domain[]=['engineering','hr','marketing','operations','finance'];
const BUSINESS:BusinessStrategy[]=['short_term_profit','growth','downside_protection','balanced','adaptive'];
const KNOWLEDGE:KnowledgeStrategy[]=['rely_on_people','build_team_capability','capture_knowledge','build_networks','automate_critical_knowledge','buy_expertise','no_particular_strategy'];
const POSTURES:RiskPosture[]=['bullish','balanced','risk_averse'];
const COST:Record<Intervention,number>={river:18,intranet:35,expert_deploy:25,expert_coach:20,expert_capture:25,cop:25,training:35,automation:110,aar:15,external:55};

class RNG{constructor(public s:number){}next(){this.s=(this.s*1664525+1013904223)>>>0;return this.s/4294967296}int(n:number){return Math.floor(this.next()*n)}pick<T>(a:T[]){return a[this.int(a.length)]}chance(p:number){return this.next()<p}}
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const mean=(a:number[])=>a.reduce((s,x)=>s+x,0)/Math.max(1,a.length);
const rec=<T extends string>(keys:T[],v:number)=>Object.fromEntries(keys.map(k=>[k,v])) as Record<T,number>;

interface Site{team:Record<Domain,number>;docs:Record<Domain,number>}
interface Company{turnover:number;sites:Site[];intranet:Record<Domain,number>;experts:Record<Domain,number>;expertPressure:Record<Domain,number>;cop:Set<Domain>;automated:Set<Domain>;lessons:Record<Domain,number>}
interface EventView{round:number;domain:Domain;difficulty:number;impact:number;criticality:number;repeatability:number;novelty:number;specialisation:number;card:EventCard}
interface PlayerView{mode:Mode;round:number;actionsRemaining:number;turnover:number;businessStrategy:BusinessStrategy;knowledgeStrategy:KnowledgeStrategy;riskPosture:RiskPosture;domain:Domain;teamScores:number[];localDocs?:number[];intranet:number;expert:number;expertPressure:number;riverGap:number;copActive:boolean;automated:boolean;criticality:number;repeatability:number;novelty:number;specialisation:number}
interface Candidate{action:Intervention;domain:Domain;score:number;immediate:number;capability:number;resilience:number;cost:number;reason:string}
interface DecisionLog{session:number;company:number;mode:Mode;round:number;phase:'challenge'|'invest';businessStrategy:BusinessStrategy;knowledgeStrategy:KnowledgeStrategy;riskPosture:RiskPosture;visibleView:PlayerView;choice:string;score?:number;reason:string;alternatives:string[];outcome?:string}
interface CompanyResult{session:number;company:number;mode:Mode;businessStrategy:BusinessStrategy;knowledgeStrategy:KnowledgeStrategy;riskPosture:RiskPosture;finalTurnoverRatio:number;challengeSuccessRate:number;actionsUsed:number;actionsAvailable:number;strategyShiftRound:number|null;expertUsesByRound:number[];interventions:Record<Intervention,number>;reasonCounts:Record<string,number>}

function makeCompany(r:RNG):Company{
 const sites:Site[]=Array.from({length:6},()=>({team:rec(DOMAINS,0),docs:rec(DOMAINS,0)}));
 for(const s of sites)for(const d of DOMAINS){s.team[d]=1+r.int(3);s.docs[d]=1+r.int(3)}
 const intranet=rec(DOMAINS,2),experts=rec(DOMAINS,0),pressure=rec(DOMAINS,0),lessons=rec(DOMAINS,0);for(const d of DOMAINS)experts[d]=4+r.int(3);
 return{turnover:875,sites,intranet,experts,expertPressure:pressure,cop:new Set(),automated:new Set(),lessons};
}
function eventFor(round:number,r:RNG):EventView{
 const domain=r.pick(DOMAINS);const late=round>=7;const criticality=late?4+r.int(2):1+r.int(Math.min(5,round+1));const repeatability=late?1+r.int(3):2+r.int(4);const novelty=late?4+r.int(2):1+r.int(Math.min(5,round));const specialisation=late?4+r.int(2):1+r.int(Math.min(4,round));const difficulty=Math.min(9,2+Math.floor((round-1)*.75)+r.int(2));const impact=Math.round(18*Math.pow(1.26,round-1));const tags:string[]=[];if(late)tags.push('escalation','critical','specialist','novel');const card:EventCard={id:`AGENT-${round}-${domain}`,type:r.chance(.55)?'problem':'opportunity',scope:r.chance(.6)?'local':'corporate',title:late?`Critical specialist ${domain} disruption`:`Round ${round} ${domain} challenge`,description:'Synthetic agent-study event',domains:[{domain,difficulty}],impact,tags};return{round,domain,difficulty,impact,criticality,repeatability,novelty,specialisation,card};
}
function makeView(mode:Mode,round:number,actionsRemaining:number,c:Company,event:EventView,b:BusinessStrategy,k:KnowledgeStrategy,p:RiskPosture):PlayerView{
 const teams=c.sites.map(s=>s.team[event.domain]);const docs=c.sites.map(s=>s.docs[event.domain]);return{mode,round,actionsRemaining,turnover:c.turnover,businessStrategy:b,knowledgeStrategy:k,riskPosture:p,domain:event.domain,teamScores:teams,...(localCodifiedVisible(mode)?{localDocs:docs}:{}),intranet:c.intranet[event.domain],expert:c.experts[event.domain],expertPressure:c.expertPressure[event.domain],riverGap:Math.max(...teams)-Math.min(...teams),copActive:c.cop.has(event.domain),automated:c.automated.has(event.domain),criticality:event.criticality,repeatability:event.repeatability,novelty:event.novelty,specialisation:event.specialisation};
}
function weights(b:BusinessStrategy,k:KnowledgeStrategy,p:RiskPosture){let immediate=.4,capability=.3,resilience=.3;if(b==='short_term_profit'){immediate=.65;capability=.2;resilience=.15}if(b==='growth'){immediate=.45;capability=.4;resilience=.15}if(b==='downside_protection'){immediate=.25;capability=.25;resilience=.5}if(b==='adaptive'){immediate=.3;capability=.4;resilience=.3}if(k==='build_team_capability')capability+=.2;if(k==='capture_knowledge')resilience+=.15;if(k==='build_networks')resilience+=.15;if(k==='rely_on_people')immediate+=.15;if(p==='bullish'){immediate+=.12;resilience-=.06}if(p==='risk_averse'){resilience+=.15;immediate-=.08}const total=immediate+capability+resilience;return{immediate:immediate/total,capability:capability/total,resilience:resilience/total};}
function candidateList(v:PlayerView):Candidate[]{
 const w=weights(v.businessStrategy,v.knowledgeStrategy,v.riskPosture),d=v.domain,critical=v.criticality/5,reuse=v.repeatability/5,novel=v.novelty/5,special=v.specialisation/5,gap=v.riverGap/5,expertPhase=v.round<=2?'early':v.round<=6?'middle':'late';
 const items:{action:Intervention;immediate:number;capability:number;resilience:number;allowed:boolean;reason:string}[]=[
  {action:'river',immediate:.55+.35*gap,capability:.75*gap,resilience:.35*gap,allowed:v.riverGap>0,reason:v.riverGap>=2?'Large site gap makes direct peer transfer the fastest capability lift.':'The river has narrowed, so another direct transfer has limited marginal value.'},
  {action:'intranet',immediate:.15+.35*reuse,capability:.3+.45*reuse,resilience:.25+.55*critical*reuse,allowed:v.intranet<6,reason:critical*reuse>.45?'This knowledge is important and reusable across sites, so broad accessibility now beats another one-off transfer.':'The knowledge is not yet critical/reusable enough for broad publication to dominate.'},
  {action:'expert_deploy',immediate:expertPhase==='early'?1:expertPhase==='middle'?.35:(special>.7?.95:.25),capability:.08,resilience:expertPhase==='middle'?-.15:.05,allowed:true,reason:expertPhase==='early'?'The Expert knows more than the organisation, so direct deployment is the strongest immediate response.':expertPhase==='middle'?'Routine Expert dependence is now a bottleneck; use them only if the immediate problem justifies it.':special>.7?'This is a genuinely specialist late problem: bring the Expert back as master troubleshooter.':'Late routine work should now be handled by organisational capability, not the Expert.'},
  {action:'expert_coach',immediate:.15,capability:.75,resilience:.6,allowed:Math.min(...v.teamScores)<v.expert,reason:'Use scarce expertise to lift the organisation rather than repeatedly solving the same work.'},
  {action:'expert_capture',immediate:.1,capability:.35,resilience:.85*critical*reuse,allowed:v.mode==='expert'&&critical>.45,reason:'Selective capture is worthwhile because this knowledge is critical and vulnerable, not because more content is inherently better.'},
  {action:'cop',immediate:.08+.18*novel,capability:.35+.3*novel,resilience:.55+.35*novel,allowed:!v.copActive,reason:'A network has weak instant ROI but strong value for unfamiliar future questions.'},
  {action:'training',immediate:.05,capability:.7,resilience:.5,allowed:Math.min(...v.teamScores)<5,reason:'Training is delayed but persistent capability; it is better before the next crisis than during it.'},
  {action:'automation',immediate:.55*reuse*(1-novel),capability:.25,resilience:.45*reuse*(1-novel),allowed:!v.automated&&v.repeatability>=4&&v.novelty<=2,reason:'Automation pays only when the knowledge is stable and repeatable.'},
  {action:'aar',immediate:.05,capability:.35,resilience:.45,allowed:true,reason:'A lesson has modest immediate payoff but compounds if this pattern recurs.'},
  {action:'external',immediate:.65*special,capability:.02,resilience:.02,allowed:special>.75&&v.expert<5,reason:'Buy expertise only when the problem is genuinely beyond current internal capability.'},
 ];
 return items.filter(x=>x.allowed).map(x=>{let strategic=0;if(v.knowledgeStrategy==='build_team_capability'&&['river','expert_coach','training'].includes(x.action))strategic+=.18;if(v.knowledgeStrategy==='capture_knowledge'&&['intranet','expert_capture','aar'].includes(x.action))strategic+=.18;if(v.knowledgeStrategy==='build_networks'&&x.action==='cop')strategic+=.25;if(v.knowledgeStrategy==='automate_critical_knowledge'&&x.action==='automation')strategic+=.25;if(v.knowledgeStrategy==='buy_expertise'&&x.action==='external')strategic+=.22;if(v.knowledgeStrategy==='rely_on_people'&&x.action==='expert_deploy')strategic+=.2;const gross=w.immediate*x.immediate+w.capability*x.capability+w.resilience*x.resilience+strategic;const pricePenalty=COST[x.action]/Math.max(120,v.turnover)*(v.riskPosture==='risk_averse'?1.6:v.riskPosture==='bullish'?.8:1.1);return{action:x.action,domain:d,score:gross-pricePenalty,immediate:x.immediate,capability:x.capability,resilience:x.resilience,cost:COST[x.action],reason:x.reason};}).sort((a,b)=>b.score-a.score);
}
function applyInvestment(c:Company,a:Candidate,v:PlayerView){const d=a.domain;c.turnover=Math.max(0,c.turnover-a.cost);switch(a.action){case'river':{const lo=[...c.sites].sort((x,y)=>x.team[d]-y.team[d])[0],hi=[...c.sites].sort((x,y)=>y.team[d]-x.team[d])[0];lo.team[d]=Math.max(lo.team[d],Math.round(hi.team[d]*.8));break}case'intranet':c.intranet[d]=Math.min(6,c.intranet[d]+1);break;case'expert_deploy':c.expertPressure[d]++;break;case'expert_coach':{const lo=[...c.sites].sort((x,y)=>x.team[d]-y.team[d])[0];lo.team[d]=Math.min(6,lo.team[d]+1);break}case'expert_capture':c.intranet[d]=Math.min(6,c.intranet[d]+1);break;case'cop':c.cop.add(d);break;case'training':{for(const s of c.sites)if(s.team[d]<4)s.team[d]++;break}case'automation':c.automated.add(d);break;case'aar':c.lessons[d]++;break;case'external':break;}}
function challengeDecision(v:PlayerView,event:EventView){const base=Math.max(...v.teamScores,v.intranet);const expertMod=expertCurveModifier(v.mode,v.round,event.card);const expertKnowledge=v.expert+expertMod;const options=[{name:'internal',knowledge:base,cost:0,reason:'Use existing organisational capability.'},{name:'expert',knowledge:expertKnowledge,cost:25,reason:expertCurveLabel(v.mode,v.round,event.card)==='troubleshooter'?'The late challenge is specialist; this is the moment deep expertise becomes decisive again.':v.round<=2?'The Expert has the strongest knowledge now.':'Prefer organisational capability unless the Expert materially changes the odds.'},{name:'network',knowledge:v.copActive?base+2:base,cost:0,reason:'Use distributed tacit access for unfamiliar work.'},{name:'automation',knowledge:v.automated&&v.novelty<=2?base+2:base,cost:0,reason:'Automation helps stable work, not novel troubleshooting.'}];const scored=options.map(o=>({...o,p:clamp((13-Math.max(1,event.difficulty+1-o.knowledge))/12,0,1),value:clamp((13-Math.max(1,event.difficulty+1-o.knowledge))/12,0,1)*event.impact-o.cost})).sort((a,b)=>b.value-a.value);return{chosen:scored[0],alternatives:scored.slice(1,3)};}

const logs:DecisionLog[]=[];const results:CompanyResult[]=[];
for(let session=1;session<=30;session++){
 const mode:Mode=session<=20?'newbie':'expert';const marketRng=new RNG(810000+session);const events=Array.from({length:8},(_,i)=>eventFor(i+1,marketRng));
 for(let companyNo=1;companyNo<=5;companyNo++){
  const r=new RNG(910000+session*20+companyNo),c=makeCompany(r);const business=BUSINESS[(companyNo+session)%BUSINESS.length],knowledge=KNOWLEDGE[(companyNo*2+session)%KNOWLEDGE.length],posture=POSTURES[(companyNo+session*2)%POSTURES.length];const initial=c.turnover;let successes=0,uses=0,shiftRound:number|null=null;const expertUsesByRound=Array(8).fill(0);const interventions=Object.fromEntries((['river','intranet','expert_deploy','expert_coach','expert_capture','cop','training','automation','aar','external'] as Intervention[]).map(x=>[x,0])) as Record<Intervention,number>;const reasonCounts:Record<string,number>={};let previousTop='';
  for(let round=1;round<=8;round++){
   const event=events[round-1];let view=makeView(mode,round,defaultActionsForMode(mode),c,event,business,knowledge,posture);const ch=challengeDecision(view,event);const success=r.chance(ch.chosen.p);if(success)successes++;else if(event.card.type==='problem')c.turnover=Math.max(0,c.turnover-event.impact);else if(success)c.turnover+=event.impact;if(ch.chosen.name==='expert'){expertUsesByRound[round-1]++;c.expertPressure[event.domain]++;}logs.push({session,company:companyNo,mode,round,phase:'challenge',businessStrategy:business,knowledgeStrategy:knowledge,riskPosture:posture,visibleView:view,choice:ch.chosen.name,reason:ch.chosen.reason,alternatives:ch.alternatives.map(x=>`${x.name}: ${Math.round(x.p*100)}%`),outcome:success?'success':'failure'});
   let actions=defaultActionsForMode(mode),guard=0;while(actions>0&&guard++<20){view=makeView(mode,round,actions,c,event,business,knowledge,posture);const candidates=candidateList(view).filter(x=>x.cost<=c.turnover);const best=candidates[0];if(!best||best.score<=.12){logs.push({session,company:companyNo,mode,round,phase:'invest',businessStrategy:business,knowledgeStrategy:knowledge,riskPosture:posture,visibleView:view,choice:'stop',reason:'No remaining visible intervention produces enough marginal value for this strategy at this point.',alternatives:candidates.slice(0,3).map(x=>`${x.action} ${x.score.toFixed(2)}`)});break;}applyInvestment(c,best,view);uses++;actions--;interventions[best.action]++;reasonCounts[best.action]=(reasonCounts[best.action]||0)+1;logs.push({session,company:companyNo,mode,round,phase:'invest',businessStrategy:business,knowledgeStrategy:knowledge,riskPosture:posture,visibleView:view,choice:best.action,score:best.score,reason:best.reason,alternatives:candidates.slice(1,4).map(x=>`${x.action} ${x.score.toFixed(2)}`),outcome:`spent $${best.cost}k`});const nowTop=candidateList(makeView(mode,round,actions,c,event,business,knowledge,posture))[0]?.action||'';if(previousTop&&nowTop&&nowTop!==previousTop&&shiftRound==null&&round>=3)shiftRound=round;previousTop=nowTop;}
  }
  results.push({session,company:companyNo,mode,businessStrategy:business,knowledgeStrategy:knowledge,riskPosture:posture,finalTurnoverRatio:c.turnover/initial,challengeSuccessRate:successes/8,actionsUsed:uses,actionsAvailable:8*defaultActionsForMode(mode),strategyShiftRound:shiftRound,expertUsesByRound,interventions,reasonCounts});
 }
}
function summarize(mode:Mode){const rr=results.filter(x=>x.mode===mode);const investLogs=logs.filter(x=>x.mode===mode&&x.phase==='invest'&&x.choice!=='stop');const challengeLogs=logs.filter(x=>x.mode===mode&&x.phase==='challenge');const byAction=Object.fromEntries((['river','intranet','expert_deploy','expert_coach','expert_capture','cop','training','automation','aar','external'] as Intervention[]).map(a=>[a,investLogs.filter(x=>x.choice===a).length]));const expertByRound=Array.from({length:8},(_,i)=>challengeLogs.filter(x=>x.round===i+1&&x.choice==='expert').length);const topReasons=[...investLogs.reduce((m,l)=>m.set(l.reason,(m.get(l.reason)||0)+1),new Map<string,number>())].sort((a,b)=>b[1]-a[1]).slice(0,8);return{companies:rr.length,successRate:mean(rr.map(x=>x.challengeSuccessRate)),turnoverRatio:mean(rr.map(x=>x.finalTurnoverRatio)),actionsUsedRatio:mean(rr.map(x=>x.actionsUsed/x.actionsAvailable)),strategyShiftRate:rr.filter(x=>x.strategyShiftRound!=null).length/rr.length,meanShiftRound:mean(rr.filter(x=>x.strategyShiftRound!=null).map(x=>x.strategyShiftRound!)),expertChallengeUsesByRound:expertByRound,investmentUses:byAction,topReasons};}
const summary={generatedAt:new Date().toISOString(),description:'30 eight-round synthetic sessions, one agent per company, five companies/session: 20 Newbie and 10 Expert. Agents observe a mode-filtered player view, generate and rank value-producing actions, retry after each action, and record a concise rule-based rationale. No Neon writes.',counts:{sessions:30,companies:150,newbieSessions:20,expertSessions:10},newbie:summarize('newbie'),expert:summarize('expert')};
mkdirSync('balance-results',{recursive:true});writeFileSync('balance-results/agent-player-study.json',JSON.stringify({summary,results,logs},null,2));
const csv=['session,company,mode,businessStrategy,knowledgeStrategy,riskPosture,finalTurnoverRatio,challengeSuccessRate,actionsUsed,actionsAvailable,strategyShiftRound',...results.map(x=>[x.session,x.company,x.mode,x.businessStrategy,x.knowledgeStrategy,x.riskPosture,x.finalTurnoverRatio.toFixed(3),x.challengeSuccessRate.toFixed(3),x.actionsUsed,x.actionsAvailable,x.strategyShiftRound??''].join(','))].join('\n');writeFileSync('balance-results/agent-player-study.csv',csv);
const md=`# Agent-style five-company study\n\nGenerated: ${summary.generatedAt}\n\n30 eight-round games: **20 Newbie + 10 Expert**, five one-player companies per game. Agents only see the mode-filtered player view; Newbie agents do not see Local Codified Knowledge. Each decision stores the visible inputs, selected action, alternatives and a short rule-based rationale.\n\n## Newbie\n- Challenge success: ${(summary.newbie.successRate*100).toFixed(1)}%\n- Actions used: ${(summary.newbie.actionsUsedRatio*100).toFixed(1)}%\n- Strategy-shift signal: ${(summary.newbie.strategyShiftRate*100).toFixed(1)}%\n- Expert challenge uses by round: ${summary.newbie.expertChallengeUsesByRound.join(', ')}\n- Investment mix: ${Object.entries(summary.newbie.investmentUses).map(([k,v])=>`${k} ${v}`).join(' · ')}\n\n## Expert\n- Challenge success: ${(summary.expert.successRate*100).toFixed(1)}%\n- Actions used: ${(summary.expert.actionsUsedRatio*100).toFixed(1)}%\n- Strategy-shift signal: ${(summary.expert.strategyShiftRate*100).toFixed(1)}%\n- Expert challenge uses by round: ${summary.expert.expertChallengeUsesByRound.join(', ')}\n- Investment mix: ${Object.entries(summary.expert.investmentUses).map(([k,v])=>`${k} ${v}`).join(' · ')}\n\n## Most common Newbie rationales\n${summary.newbie.topReasons.map(([r,n])=>`- ${n}× ${r}`).join('\n')}\n\n## Most common Expert rationales\n${summary.expert.topReasons.map(([r,n])=>`- ${n}× ${r}`).join('\n')}\n`;
writeFileSync('balance-results/agent-player-study.md',md);console.log('\n=== AGENT-STYLE FIVE-COMPANY STUDY ===');console.log(summary);console.log('\n'+md);
