import { mkdirSync, writeFileSync } from 'node:fs';
import { defaultActionsForMode, expertCurveLabel, expertCurveModifier, localCodifiedVisible } from '../src/engine/learningCurveBalanceV1.ts';
import type { BusinessStrategy, ExperienceMode, KnowledgeStrategy } from '../src/types/gameV2.ts';
import type { EventCard, KnowledgeDomain } from '../src/types/game.ts';

type Mode=ExperienceMode; type Domain=KnowledgeDomain; type RiskPosture='bullish'|'balanced'|'risk_averse';
type Invest='river'|'intranet'|'expert_coach'|'expert_capture'|'cop'|'training'|'automation'|'aar';
type Response='internal'|'expert'|'network'|'automation'|'external';
const DOMAINS:Domain[]=['engineering','hr','marketing','operations','finance'];
const BUSINESS:BusinessStrategy[]=['short_term_profit','growth','downside_protection','balanced','adaptive'];
const KNOWLEDGE:KnowledgeStrategy[]=['rely_on_people','build_team_capability','capture_knowledge','build_networks','automate_critical_knowledge','buy_expertise','no_particular_strategy'];
const POSTURES:RiskPosture[]=['bullish','balanced','risk_averse'];
const COST:Record<Invest,number>={river:18,intranet:35,expert_coach:20,expert_capture:25,cop:25,training:55,automation:110,aar:15};
class RNG{constructor(public s:number){}next(){this.s=(this.s*1664525+1013904223)>>>0;return this.s/4294967296}int(n:number){return Math.floor(this.next()*n)}pick<T>(a:T[]){return a[this.int(a.length)]}chance(p:number){return this.next()<p}}
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v)); const mean=(a:number[])=>a.reduce((s,x)=>s+x,0)/Math.max(1,a.length); const rec=<T extends string>(keys:T[],v:number)=>Object.fromEntries(keys.map(k=>[k,v])) as Record<T,number>;
interface Site{team:Record<Domain,number>;docs:Record<Domain,number>}
interface Company{turnover:number;sites:Site[];intranet:Record<Domain,number>;experts:Record<Domain,number>;expertPressure:Record<Domain,number>;cop:Set<Domain>;automated:Set<Domain>;lessons:Record<Domain,number>;critical:Record<Domain,number>;reuse:Record<Domain,number>;novelty:Record<Domain,number>}
interface EventView{round:number;move:number;domain:Domain;difficulty:number;impact:number;criticality:number;repeatability:number;novelty:number;specialisation:number;card:EventCard}
interface VisibleDomain{domain:Domain;team:number[];localDocs?:number[];intranet:number;expert:number;expertPressure:number;riverGap:number;cop:boolean;automated:boolean;observedCriticality:number;observedReuse:number;observedNovelty:number;lessons:number}
interface PlayerView{mode:Mode;round:number;actionsRemaining:number;turnover:number;businessStrategy:BusinessStrategy;knowledgeStrategy:KnowledgeStrategy;riskPosture:RiskPosture;domains:VisibleDomain[];currentChallenge:{domain:Domain;difficulty:number;impact:number;criticality:number;repeatability:number;novelty:number;specialisation:number}}
interface Candidate{action:Invest;domain:Domain;score:number;cost:number;immediate:number;capability:number;resilience:number;reason:string}
interface DecisionLog{session:number;company:number;mode:Mode;round:number;move?:number;phase:'challenge'|'invest';businessStrategy:BusinessStrategy;knowledgeStrategy:KnowledgeStrategy;riskPosture:RiskPosture;choice:string;domain:Domain;reason:string;alternatives:string[];score?:number;outcome?:string;visibleSummary:string}
interface Result{session:number;company:number;mode:Mode;businessStrategy:BusinessStrategy;knowledgeStrategy:KnowledgeStrategy;riskPosture:RiskPosture;successRate:number;turnoverRatio:number;actionsUsed:number;actionsAvailable:number;shiftRound:number|null;responsesByRound:Record<Response,number[]>;investments:Record<Invest,number>}
function makeCompany(r:RNG):Company{const sites=Array.from({length:6},()=>({team:rec(DOMAINS,0),docs:rec(DOMAINS,0)}));for(const s of sites)for(const d of DOMAINS){s.team[d]=1+r.int(3);s.docs[d]=1+r.int(3)}const intranet=rec(DOMAINS,2),experts=rec(DOMAINS,0),pressure=rec(DOMAINS,0);for(const d of DOMAINS)experts[d]=4+r.int(3);return{turnover:875,sites,intranet,experts,expertPressure:pressure,cop:new Set(),automated:new Set(),lessons:rec(DOMAINS,0),critical:rec(DOMAINS,0),reuse:rec(DOMAINS,0),novelty:rec(DOMAINS,0)}}
function eventFor(round:number,move:number,r:RNG):EventView{const d=r.pick(DOMAINS),late=round>=7,criticality=late?4+r.int(2):1+r.int(Math.min(5,round+1)),repeatability=late?1+r.int(3):2+r.int(4),novelty=late?4+r.int(2):1+r.int(Math.max(1,Math.min(5,round))),specialisation=late?4+r.int(2):1+r.int(Math.max(1,Math.min(4,round))),difficulty=Math.min(9,2+Math.floor((round-1)*.7)+r.int(2)),impact=Math.round((round===1?35:45)*Math.pow(1.28,round-1));const tags=late?['escalation','critical','specialist','novel']:[];const card:EventCard={id:`AG2-${round}-${move}-${d}`,type:r.chance(.55)?'problem':'opportunity',scope:r.chance(.6)?'local':'enterprise',title:late?`Specialist ${d} disruption`:`Round ${round} ${d} challenge`,description:'Agent study event',domains:[{domain:d,difficulty}],impact,tags};return{round,move,domain:d,difficulty,impact,criticality,repeatability,novelty,specialisation,card}}
function observe(c:Company,e:EventView){const d=e.domain;c.critical[d]=Math.max(c.critical[d],e.criticality);c.reuse[d]=Math.max(c.reuse[d],e.repeatability);c.novelty[d]=Math.max(c.novelty[d],e.novelty)}
function visibleDomain(mode:Mode,c:Company,d:Domain):VisibleDomain{const team=c.sites.map(s=>s.team[d]),docs=c.sites.map(s=>s.docs[d]);return{domain:d,team,...(localCodifiedVisible(mode)?{localDocs:docs}:{}),intranet:c.intranet[d],expert:c.experts[d],expertPressure:c.expertPressure[d],riverGap:Math.max(...team)-Math.min(...team),cop:c.cop.has(d),automated:c.automated.has(d),observedCriticality:c.critical[d],observedReuse:c.reuse[d],observedNovelty:c.novelty[d],lessons:c.lessons[d]}}
function playerView(mode:Mode,round:number,actions:number,c:Company,e:EventView,b:BusinessStrategy,k:KnowledgeStrategy,p:RiskPosture):PlayerView{return{mode,round,actionsRemaining:actions,turnover:c.turnover,businessStrategy:b,knowledgeStrategy:k,riskPosture:p,domains:DOMAINS.map(d=>visibleDomain(mode,c,d)),currentChallenge:{domain:e.domain,difficulty:e.difficulty,impact:e.impact,criticality:e.criticality,repeatability:e.repeatability,novelty:e.novelty,specialisation:e.specialisation}}}
function weights(b:BusinessStrategy,k:KnowledgeStrategy,p:RiskPosture){let immediate=.4,capability=.3,resilience=.3;if(b==='short_term_profit'){immediate=.65;capability=.2;resilience=.15}else if(b==='growth'){immediate=.45;capability=.4;resilience=.15}else if(b==='downside_protection'){immediate=.25;capability=.25;resilience=.5}else if(b==='adaptive'){immediate=.3;capability=.4;resilience=.3}if(k==='build_team_capability')capability+=.18;if(k==='capture_knowledge')resilience+=.15;if(k==='build_networks')resilience+=.12;if(k==='rely_on_people')immediate+=.1;if(p==='bullish'){immediate+=.1;resilience-=.05}if(p==='risk_averse'){resilience+=.14;immediate-=.07}const t=immediate+capability+resilience;return{immediate:immediate/t,capability:capability/t,resilience:resilience/t}}
function candidates(v:PlayerView):Candidate[]{const w=weights(v.businessStrategy,v.knowledgeStrategy,v.riskPosture),out:Candidate[]=[];for(const x of v.domains){const minTeam=Math.min(...x.team),maxTeam=Math.max(...x.team),avgTeam=mean(x.team),gap=x.riverGap/5,coachNeed=clamp((x.expert-avgTeam)/5,0,1),critical=x.observedCriticality/5,reuse=x.observedReuse/5,novel=x.observedNovelty/5,sourceCeiling=Math.max(maxTeam,x.expert,...(x.localDocs||[]));const push=(action:Invest,allowed:boolean,immediate:number,capability:number,resilience:number,reason:string,bonus=0)=>{if(!allowed)return;const cost=COST[action],price=(cost/Math.max(150,v.turnover))*(v.riskPosture==='risk_averse'?1.8:v.riskPosture==='bullish'?.85:1.2),score=w.immediate*immediate+w.capability*capability+w.resilience*resilience+bonus-price;out.push({action,domain:x.domain,score,cost,immediate,capability,resilience,reason})};
 push('river',x.riverGap>0,.45+.35*gap,.75*gap,.3*gap,x.riverGap>=2?'A large River gap makes direct site-to-site sharing the quickest cheap lift.':'The River has narrowed; direct sharing still helps, but its marginal capability lift is now small.',v.knowledgeStrategy==='build_team_capability'?.12:0);
 push('intranet',x.intranet<sourceCeiling,.12+.32*reuse,.25+.45*reuse,.2+.65*critical*reuse,critical*reuse>=.45?'Observed knowledge is both important and reusable; one corporate access point now reaches more people than another one-off transfer.':'There is publishable knowledge, but its observed criticality/reuse is not yet high enough to make capture automatically superior.',v.knowledgeStrategy==='capture_knowledge'?.16:0);
 push('expert_coach',minTeam<x.expert,.08,.72*coachNeed,.62*coachNeed,'Use the Expert to build capability in weaker teams instead of repeatedly making the Expert the responder.',v.knowledgeStrategy==='build_team_capability'?.15:0);
 push('expert_capture',v.mode==='expert'&&critical>=.6&&reuse>=.4&&x.intranet<sourceCeiling,.05,.3*reuse,.9*critical*reuse,'Capture this Expert knowledge selectively because it is critical, reusable and vulnerable — not because more content is inherently better.',v.knowledgeStrategy==='capture_knowledge'?.2:0);
 push('cop',!x.cop,.05+.15*novel,.3+.25*novel,.52+.35*novel,'A network has modest immediate ROI but becomes valuable as questions become less predictable.',v.knowledgeStrategy==='build_networks'?.22:0);
 push('training',minTeam<4,.03,.55*clamp((4-avgTeam)/3,0,1),.45*clamp((4-avgTeam)/3,0,1),'Training is slower than direct transfer but creates persistent distributed capability.',v.knowledgeStrategy==='build_team_capability'?.1:0);
 push('automation',v.round>=4&&!x.automated&&x.observedReuse>=4&&x.observedNovelty<=2,.5*reuse*(1-novel),.18,.4*reuse*(1-novel),'Automation is attractive only after the work proves stable and repeatable.',v.knowledgeStrategy==='automate_critical_knowledge'?.25:0);
 push('aar',x.lessons<2,.03,.25,.38+critical*.15,'An AAR has little instant glamour but preserves learning from events that may recur.',0);
 }
 return out.sort((a,b)=>b.score-a.score)}
function reserve(posture:RiskPosture){return posture==='bullish'?.14:posture==='risk_averse'?.34:.24}
function apply(c:Company,a:Candidate){const d=a.domain;c.turnover=Math.max(0,c.turnover-a.cost);if(a.action==='river'){const sorted=[...c.sites].sort((p,q)=>p.team[d]-q.team[d]),lo=sorted[0],hi=sorted.at(-1)!;lo.team[d]=Math.max(lo.team[d],Math.min(6,Math.round(hi.team[d]*.8)))}else if(a.action==='intranet'||a.action==='expert_capture')c.intranet[d]=Math.min(6,c.intranet[d]+1);else if(a.action==='expert_coach'){const lo=[...c.sites].sort((p,q)=>p.team[d]-q.team[d])[0];lo.team[d]=Math.min(6,lo.team[d]+1)}else if(a.action==='cop')c.cop.add(d);else if(a.action==='training'){for(const s of c.sites)if(s.team[d]<4)s.team[d]++}else if(a.action==='automation')c.automated.add(d);else if(a.action==='aar')c.lessons[d]++}
function successProb(k:number,d:number){return clamp((13-Math.max(1,d+1-k))/12,0,1)}
function response(v:PlayerView,e:EventView):{choice:Response;p:number;reason:string;alternatives:string[];cost:number}{const x=v.domains.find(z=>z.domain===e.domain)!,internal=Math.max(...x.team,x.intranet),curve=expertCurveModifier(v.mode,v.round,e.card),expert=x.expert+curve,phase=expertCurveLabel(v.mode,v.round,e.card),stable=e.repeatability>=4&&e.novelty<=2;const options:{choice:Response;k:number;cost:number;reason:string}[]=[{choice:'internal',k:internal,cost:0,reason:'Use capability already distributed through teams and the corporate knowledge base.'},{choice:'expert',k:expert,cost:v.round<=2?0:(phase==='troubleshooter'?10:25),reason:v.round<=2?'The Expert knows materially more than the organisation, so using them now is the highest-confidence response.':phase==='troubleshooter'?'This is the exceptional specialist problem the Expert should be reserved for: bring the master troubleshooter back.':'Routine dependence on the Expert is now less attractive than organisational capability.'},{choice:'network',k:x.cop?internal+2:internal,cost:0,reason:'Use distributed tacit access when the network can add knowledge beyond the local organisation.'},{choice:'automation',k:x.automated&&stable?internal+2:internal,cost:0,reason:'Automation helps stable repeatable work, not novel specialist troubleshooting.'}];if(e.specialisation>=5&&internal<e.difficulty)options.push({choice:'external',k:e.difficulty+2,cost:55,reason:'The challenge sits above the current internal north bank, so external expertise is rational.'});const costWeight=v.riskPosture==='risk_averse'?1.1:v.riskPosture==='bullish'?.65:.85;const ranked=options.map(o=>({...o,p:successProb(o.k,e.difficulty),utility:successProb(o.k,e.difficulty)*e.impact-o.cost*costWeight-(o.choice==='expert'&&v.round>=3&&v.round<=6?x.expertPressure*4:0)})).sort((a,b)=>b.utility-a.utility);return{choice:ranked[0].choice,p:ranked[0].p,reason:ranked[0].reason,cost:ranked[0].cost,alternatives:ranked.slice(1,4).map(o=>`${o.choice} ${Math.round(o.p*100)}% / utility ${o.utility.toFixed(1)}`)}}
function summaryText(v:PlayerView,d:Domain){const x=v.domains.find(z=>z.domain===d)!;return`${d}: team ${Math.min(...x.team)}-${Math.max(...x.team)}, corporate ${x.intranet}, expert ${x.expert}, river gap ${x.riverGap}, critical ${x.observedCriticality}, reuse ${x.observedReuse}, novelty ${x.observedNovelty}${v.mode==='expert'?`, local docs ${Math.min(...(x.localDocs||[]))}-${Math.max(...(x.localDocs||[]))}`:''}`}
const logs:DecisionLog[]=[],results:Result[]=[];
for(let session=1;session<=30;session++){const mode:Mode=session<=20?'newbie':'expert',marketRng=new RNG(870000+session),events=Array.from({length:16},(_,i)=>eventFor(Math.floor(i/2)+1,i+1,marketRng));for(let companyNo=1;companyNo<=5;companyNo++){const r=new RNG(970000+session*20+companyNo),c=makeCompany(r),business=BUSINESS[(companyNo+session)%BUSINESS.length],knowledge=KNOWLEDGE[(companyNo*2+session)%KNOWLEDGE.length],posture=POSTURES[(companyNo+session*2)%POSTURES.length],initial=875;let successes=0,challengeCount=0,actionsUsed=0,shiftRound:number|null=null,priorRoundDominant='';const responsesByRound=Object.fromEntries((['internal','expert','network','automation','external'] as Response[]).map(x=>[x,Array(8).fill(0)])) as Record<Response,number[]>;const investments=Object.fromEntries((['river','intranet','expert_coach','expert_capture','cop','training','automation','aar'] as Invest[]).map(x=>[x,0])) as Record<Invest,number>;
 for(let round=1;round<=8;round++){const roundEvents=events.slice((round-1)*2,round*2);for(const e of roundEvents){observe(c,e);const v=playerView(mode,round,defaultActionsForMode(mode),c,e,business,knowledge,posture),dec=response(v,e),ok=r.chance(dec.p);challengeCount++;if(ok){successes++;if(e.card.type==='opportunity')c.turnover+=e.impact}else if(e.card.type==='problem')c.turnover=Math.max(0,c.turnover-e.impact);if(dec.cost)c.turnover=Math.max(0,c.turnover-dec.cost);if(dec.choice==='expert')c.expertPressure[e.domain]++;responsesByRound[dec.choice][round-1]++;logs.push({session,company:companyNo,mode,round,move:e.move,phase:'challenge',businessStrategy:business,knowledgeStrategy:knowledge,riskPosture:posture,choice:dec.choice,domain:e.domain,reason:dec.reason,alternatives:dec.alternatives,outcome:ok?'success':'failure',visibleSummary:summaryText(v,e.domain)})}
  let actions=defaultActionsForMode(mode),guard=0;const roundChoices:string[]=[];const anchorEvent=roundEvents[1];while(actions>0&&guard++<30){const v=playerView(mode,round,actions,c,anchorEvent,business,knowledge,posture),minCash=initial*reserve(posture)*(v.currentChallenge.criticality>=4?.75:1),list=candidates(v).filter(x=>c.turnover-x.cost>=minCash),best=list[0];if(!best||best.score<.16){logs.push({session,company:companyNo,mode,round,phase:'invest',businessStrategy:business,knowledgeStrategy:knowledge,riskPosture:posture,choice:'stop',domain:anchorEvent.domain,reason:'No remaining visible intervention creates enough marginal performance, capability or resilience value after cost and cash-reserve trade-offs.',alternatives:list.slice(0,3).map(x=>`${x.action}/${x.domain} ${x.score.toFixed(2)}`),visibleSummary:summaryText(v,anchorEvent.domain)});break}apply(c,best);actions--;actionsUsed++;investments[best.action]++;roundChoices.push(best.action);logs.push({session,company:companyNo,mode,round,phase:'invest',businessStrategy:business,knowledgeStrategy:knowledge,riskPosture:posture,choice:best.action,domain:best.domain,score:best.score,reason:best.reason,alternatives:list.slice(1,4).map(x=>`${x.action}/${x.domain} ${x.score.toFixed(2)}`),outcome:`spent $${best.cost}k`,visibleSummary:summaryText(v,best.domain)})}
  const dominant=roundChoices.length?[...roundChoices.reduce((m,x)=>m.set(x,(m.get(x)||0)+1),new Map<string,number>())].sort((a,b)=>b[1]-a[1])[0][0]:'';if(round>=3&&priorRoundDominant&&dominant&&dominant!==priorRoundDominant&&shiftRound==null)shiftRound=round;if(dominant)priorRoundDominant=dominant;
 }
 results.push({session,company:companyNo,mode,businessStrategy:business,knowledgeStrategy:knowledge,riskPosture:posture,successRate:successes/challengeCount,turnoverRatio:c.turnover/initial,actionsUsed,actionsAvailable:8*defaultActionsForMode(mode),shiftRound,responsesByRound,investments})}}
function summarize(mode:Mode){const rr=results.filter(x=>x.mode===mode),ll=logs.filter(x=>x.mode===mode),invest=ll.filter(x=>x.phase==='invest'&&x.choice!=='stop'),challenge=ll.filter(x=>x.phase==='challenge');const responseByRound=Object.fromEntries((['internal','expert','network','automation','external'] as Response[]).map(a=>[a,Array.from({length:8},(_,i)=>challenge.filter(x=>x.choice===a&&x.round===i+1).length)]));const investByRound=Object.fromEntries((['river','intranet','expert_coach','expert_capture','cop','training','automation','aar'] as Invest[]).map(a=>[a,Array.from({length:8},(_,i)=>invest.filter(x=>x.choice===a&&x.round===i+1).length)]));const reasons=[...ll.reduce((m,l)=>m.set(l.reason,(m.get(l.reason)||0)+1),new Map<string,number>())].sort((a,b)=>b[1]-a[1]).slice(0,12);return{companies:rr.length,successRate:mean(rr.map(x=>x.successRate)),turnoverRatio:mean(rr.map(x=>x.turnoverRatio)),actionsUsedRatio:mean(rr.map(x=>x.actionsUsed/x.actionsAvailable)),strategyShiftRate:rr.filter(x=>x.shiftRound!=null).length/rr.length,meanShiftRound:mean(rr.filter(x=>x.shiftRound!=null).map(x=>x.shiftRound!)),responseByRound,investByRound,reasons}}
const summary={generatedAt:new Date().toISOString(),description:'Second-generation agent study: 30 eight-round games, two Challenges per round, five one-player companies per game (20 Newbie / 10 Expert). Agents receive only mode-visible information, search across all domains for value-generating Invest actions, preserve a posture-dependent cash reserve, and record concise decision rationales. No Neon writes.',counts:{sessions:30,companies:150,newbieCompanies:100,expertCompanies:50},newbie:summarize('newbie'),expert:summarize('expert')};
mkdirSync('balance-results',{recursive:true});writeFileSync('balance-results/agent-player-study-v2.json',JSON.stringify({summary,results,logs},null,2));writeFileSync('balance-results/agent-player-study-v2.csv',['session,company,mode,businessStrategy,knowledgeStrategy,riskPosture,successRate,turnoverRatio,actionsUsed,actionsAvailable,shiftRound',...results.map(x=>[x.session,x.company,x.mode,x.businessStrategy,x.knowledgeStrategy,x.riskPosture,x.successRate.toFixed(3),x.turnoverRatio.toFixed(3),x.actionsUsed,x.actionsAvailable,x.shiftRound??''].join(','))].join('\n'));
const line=(a:number[])=>a.join(', ');const md=`# Agent-style five-company study V2\n\n30 eight-round games, two Challenges/round: **20 Newbie + 10 Expert**, five one-player companies/game. Reasoning is rule-based and limited to information exposed by that mode.\n\n## Newbie\n- Challenge success ${(summary.newbie.successRate*100).toFixed(1)}% · ending turnover ${(summary.newbie.turnoverRatio*100).toFixed(1)}% · Actions used ${(summary.newbie.actionsUsedRatio*100).toFixed(1)}%\n- Strategy shift ${(summary.newbie.strategyShiftRate*100).toFixed(1)}%, mean round ${summary.newbie.meanShiftRound.toFixed(1)}\n- Expert challenge use by round: ${line(summary.newbie.responseByRound.expert)}\n- River by round: ${line(summary.newbie.investByRound.river)}\n- Intranet by round: ${line(summary.newbie.investByRound.intranet)}\n- Expert coaching by round: ${line(summary.newbie.investByRound.expert_coach)}\n\n## Expert\n- Challenge success ${(summary.expert.successRate*100).toFixed(1)}% · ending turnover ${(summary.expert.turnoverRatio*100).toFixed(1)}% · Actions used ${(summary.expert.actionsUsedRatio*100).toFixed(1)}%\n- Strategy shift ${(summary.expert.strategyShiftRate*100).toFixed(1)}%, mean round ${summary.expert.meanShiftRound.toFixed(1)}\n- Expert challenge use by round: ${line(summary.expert.responseByRound.expert)}\n- River by round: ${line(summary.expert.investByRound.river)}\n- Intranet by round: ${line(summary.expert.investByRound.intranet)}\n- Expert coaching by round: ${line(summary.expert.investByRound.expert_coach)}\n\n## Common Newbie reasoning\n${summary.newbie.reasons.slice(0,8).map(([r,n])=>`- ${n}× ${r}`).join('\n')}\n\n## Common Expert reasoning\n${summary.expert.reasons.slice(0,8).map(([r,n])=>`- ${n}× ${r}`).join('\n')}\n`;writeFileSync('balance-results/agent-player-study-v2.md',md);console.log('\n=== AGENT PLAYER STUDY V2 ===\n',summary,'\n'+md);
