import { mkdirSync, writeFileSync } from 'node:fs';
import { defaultActionsForMode, expertCurveLabel, expertCurveModifier, localCodifiedVisible } from '../src/engine/learningCurveBalanceV1.ts';
import type { BusinessStrategy, ExperienceMode, KnowledgeStrategy } from '../src/types/gameV2.ts';
import type { EventCard, KnowledgeDomain } from '../src/types/game.ts';

type Mode=ExperienceMode; type Domain=KnowledgeDomain; type Posture='bullish'|'balanced'|'risk_averse';
type Invest='river'|'intranet'|'expert_coach'|'cop'|'training'|'automation'|'aar';
type Response='internal'|'expert'|'network'|'automation'|'external';
const D:Domain[]=['engineering','hr','marketing','operations','finance'];
const B:BusinessStrategy[]=['short_term_profit','growth','downside_protection','balanced','adaptive'];
const K:KnowledgeStrategy[]=['rely_on_people','build_team_capability','capture_knowledge','build_networks','automate_critical_knowledge','buy_expertise','no_particular_strategy'];
const P:Posture[]=['bullish','balanced','risk_averse'];
const COST:Record<Invest,number>={river:18,intranet:35,expert_coach:20,cop:25,training:55,automation:110,aar:15};
class RNG{constructor(public s:number){}next(){this.s=(this.s*1664525+1013904223)>>>0;return this.s/4294967296}int(n:number){return Math.floor(this.next()*n)}pick<T>(a:T[]){return a[this.int(a.length)]}chance(p:number){return this.next()<p}}
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v)); const mean=(a:number[])=>a.reduce((s,x)=>s+x,0)/Math.max(1,a.length); const rec=<T extends string>(keys:T[],v:number)=>Object.fromEntries(keys.map(k=>[k,v])) as Record<T,number>;
interface Co{cash:number;team:Record<Domain,number[]>;docs:Record<Domain,number[]>;intranet:Record<Domain,number>;expert:Record<Domain,number>;evidence:Record<Domain,number>;seen:Record<Domain,number>;critical:Record<Domain,number>;reuse:Record<Domain,number>;cop:Set<Domain>;auto:Set<Domain>;lessons:Record<Domain,number>;expertPressure:Record<Domain,number>}
interface Ev{round:number;move:number;domain:Domain;difficulty:number;impact:number;criticality:number;repeatability:number;novelty:number;specialisation:number;kind:'routine'|'specialist'|'stable'|'network';card:EventCard}
interface Log{session:number;company:number;mode:Mode;round:number;move?:number;phase:'challenge'|'invest';choice:string;domain:Domain;reason:string;alternatives:string[];visible:string;outcome?:string}
interface Result{session:number;company:number;mode:Mode;success:number;cashRatio:number;actionsUsed:number;actionsAvailable:number;shiftRound:number|null;responseRound:Record<Response,number[]>;investRound:Record<Invest,number[]>;falseLearning:string[]}
function company(r:RNG):Co{const team=Object.fromEntries(D.map(d=>[d,Array.from({length:6},()=>1+r.int(3))])) as Record<Domain,number[]>;const docs=Object.fromEntries(D.map(d=>[d,Array.from({length:6},()=>1+r.int(3))])) as Record<Domain,number[]>;const expert=rec(D,0);for(const d of D)expert[d]=4+r.int(3);return{cash:875,team,docs,intranet:rec(D,2),expert,evidence:rec(D,0),seen:rec(D,0),critical:rec(D,0),reuse:rec(D,0),cop:new Set(),auto:new Set(),lessons:rec(D,0),expertPressure:rec(D,0)}}
function event(round:number,move:number,r:RNG):Ev{const domain=r.pick(D);let kind:Ev['kind']='routine',criticality=2+r.int(2),repeatability=2+r.int(3),novelty=1+r.int(3),specialisation=1+r.int(3);if(round>=7){kind=r.pick(['specialist','stable','network','routine'] as Ev['kind'][]);if(kind==='specialist'){criticality=5;repeatability=1+r.int(2);novelty=5;specialisation=5}else if(kind==='stable'){criticality=4;repeatability=5;novelty=1;specialisation=2}else if(kind==='network'){criticality=4;repeatability=2;novelty=5;specialisation=3}else{criticality=4;repeatability=3;novelty=2;specialisation=2}}const difficulty=round<=2?5+r.int(2):Math.min(9,4+Math.floor((round-1)*.65)+r.int(2));const impact=Math.round(30*Math.pow(1.3,round-1));const tags:string[]=[];if(kind==='specialist')tags.push('specialist','novel','critical');if(kind==='stable')tags.push('critical','repeatable');if(kind==='network')tags.push('critical','novel');const card:EventCard={id:`AG3-${round}-${move}-${domain}`,type:r.chance(.55)?'problem':'opportunity',scope:r.chance(.6)?'local':'enterprise',title:`${kind} ${domain} challenge`,description:'Agent study event',domains:[{domain,difficulty}],impact,tags};return{round,move,domain,difficulty,impact,criticality,repeatability,novelty,specialisation,kind,card}}
function observe(c:Co,e:Ev){const d=e.domain;c.seen[d]++;c.critical[d]=Math.max(c.critical[d],e.criticality);c.reuse[d]=Math.max(c.reuse[d],e.repeatability);c.evidence[d]+=e.criticality>=4?2:1}
function visible(mode:Mode,c:Co,d:Domain){const team=`${Math.min(...c.team[d])}-${Math.max(...c.team[d])}`;const recurring=c.seen[d]>=2?'recurring':'not yet recurring';const critical=c.critical[d]>=4?'critical':'ordinary';return mode==='newbie'?`${d}: team ${team}, intranet ${c.intranet[d]}, expert ${c.expert[d]}, ${recurring}, ${critical}`:`${d}: team ${team}, local docs ${Math.min(...c.docs[d])}-${Math.max(...c.docs[d])}, intranet ${c.intranet[d]}, expert ${c.expert[d]}, evidence ${c.evidence[d]}, ${recurring}, ${critical}`}
function pSuccess(k:number,d:number){return clamp((13-Math.max(1,d+1-k))/12,0,1)}
function respond(mode:Mode,c:Co,e:Ev,posture:Posture){const d=e.domain,internal=Math.max(...c.team[d],c.intranet[d],...(localCodifiedVisible(mode)?c.docs[d]:[])),phase=expertCurveLabel(mode,e.round,e.card),expert=c.expert[d]+expertCurveModifier(mode,e.round,e.card),stable=e.repeatability>=4&&e.novelty<=2;const opts:{choice:Response;k:number;cost:number;reason:string}[]=[{choice:'internal',k:internal,cost:0,reason:'Use capability already available to the team.'},{choice:'expert',k:expert,cost:e.round<=2?0:(phase==='troubleshooter'?10:25),reason:e.round<=2?'The Expert knows materially more than the organisation; use them while that advantage matters.':phase==='troubleshooter'?'This is the specialist exception: bring the Expert back as master troubleshooter.':'Routine Expert use now adds less than distributed capability.'},{choice:'network',k:c.cop.has(d)?internal+2:internal,cost:0,reason:'Use the network when the problem is novel and distributed knowledge helps.'},{choice:'automation',k:c.auto.has(d)&&stable?internal+2:internal,cost:0,reason:'Automation helps only stable, repeatable work.'}];if(e.specialisation>=5&&internal<e.difficulty)opts.push({choice:'external',k:e.difficulty+2,cost:55,reason:'The problem sits above the internal north bank; buy outside expertise.'});const cw=posture==='risk_averse'?1.1:posture==='bullish'?.65:.85;const ranked=opts.map(o=>({...o,p:pSuccess(o.k,e.difficulty),u:pSuccess(o.k,e.difficulty)*e.impact-o.cost*cw-(o.choice==='expert'&&e.round>=3&&e.round<=6?c.expertPressure[d]*5:0)})).sort((a,b)=>b.u-a.u);return{...ranked[0],alts:ranked.slice(1,3).map(x=>`${x.choice} ${Math.round(x.p*100)}%`)}}
function weights(b:BusinessStrategy,k:KnowledgeStrategy,p:Posture){let immediate=.4,cap=.3,res=.3;if(b==='short_term_profit'){immediate=.65;cap=.2;res=.15}else if(b==='growth'){immediate=.45;cap=.4;res=.15}else if(b==='downside_protection'){immediate=.25;cap=.25;res=.5}else if(b==='adaptive'){immediate=.3;cap=.4;res=.3}if(k==='build_team_capability')cap+=.15;if(k==='capture_knowledge')res+=.12;if(k==='build_networks')res+=.12;if(p==='bullish')immediate+=.08;if(p==='risk_averse')res+=.12;const t=immediate+cap+res;return{immediate:immediate/t,cap:cap/t,res:res/t}}
function investCandidates(mode:Mode,c:Co,b:BusinessStrategy,k:KnowledgeStrategy,p:Posture){const w=weights(b,k,p),out:{a:Invest;d:Domain;score:number;reason:string}[]=[];for(const d of D){const gap=Math.max(...c.team[d])-Math.min(...c.team[d]),avg=mean(c.team[d]),critical=c.critical[d]/5,reuse=c.reuse[d]/5,source=Math.max(...c.team[d],c.expert[d],...(localCodifiedVisible(mode)?c.docs[d]:[]));const push=(a:Invest,ok:boolean,i:number,cap:number,res:number,reason:string,bonus=0)=>{if(!ok)return;const price=COST[a]/Math.max(160,c.cash)*(p==='risk_averse'?1.7:p==='bullish'?.85:1.15);out.push({a,d,score:w.immediate*i+w.cap*cap+w.res*res+bonus-price,reason})};push('river',gap>0,.5+.25*(gap/5),.75*(gap/5),.25*(gap/5),gap>=2?'A large site gap makes direct sharing the quickest cheap lift.':'The River has narrowed; another transfer now gives a small marginal lift.',k==='build_team_capability'?.1:0);push('intranet',c.evidence[d]>=2&&c.intranet[d]<source,.15+.25*reuse,.25+.4*reuse,.25+.6*critical*reuse,(c.critical[d]>=4||c.seen[d]>=2)?'This knowledge has proved important or recurring; one corporate access point now beats another one-off transfer.':'Do not publish just because knowledge exists.',k==='capture_knowledge'?.14:0);push('expert_coach',Math.min(...c.team[d])<c.expert[d],.08,.6*clamp((c.expert[d]-avg)/5,0,1),.5,'Use the Expert to build team capability rather than remain the routine responder.',k==='build_team_capability'?.12:0);push('cop',!c.cop.has(d),.05,.25,.45+.25*(c.critical[d]/5),'Build a network for questions that cannot be predicted in advance.',k==='build_networks'?.18:0);push('training',Math.min(...c.team[d])<4,.03,.45,.35,'Training is slower but creates persistent distributed capability.');push('automation',c.seen[d]>=2&&!c.auto.has(d)&&c.reuse[d]>=4&&c.critical[d]>=3,.5,.15,.35,'Automate only after the work proves stable, important and repeatable.',k==='automate_critical_knowledge'?.2:0);push('aar',c.lessons[d]<2&&c.seen[d]>0,.03,.22,.35,'Use an AAR to preserve learning from something that actually happened.')}return out.sort((x,y)=>y.score-x.score)}
function apply(c:Co,x:{a:Invest;d:Domain}){const d=x.d;c.cash=Math.max(0,c.cash-COST[x.a]);if(x.a==='river'){const lo=c.team[d].indexOf(Math.min(...c.team[d])),hi=Math.max(...c.team[d]);c.team[d][lo]=Math.max(c.team[d][lo],Math.round(hi*.8));c.evidence[d]++}else if(x.a==='intranet')c.intranet[d]=Math.min(6,c.intranet[d]+1);else if(x.a==='expert_coach'){const lo=c.team[d].indexOf(Math.min(...c.team[d]));c.team[d][lo]=Math.min(6,c.team[d][lo]+1)}else if(x.a==='cop')c.cop.add(d);else if(x.a==='training')c.team[d]=c.team[d].map(v=>v<4?v+1:v);else if(x.a==='automation')c.auto.add(d);else if(x.a==='aar'){c.lessons[d]++;c.evidence[d]+=2}}
const logs:Log[]=[],results:Result[]=[];
for(let s=1;s<=30;s++){const mode:Mode=s<=20?'newbie':'expert',mr=new RNG(990000+s),events=Array.from({length:16},(_,i)=>event(Math.floor(i/2)+1,i+1,mr));for(let n=1;n<=5;n++){const r=new RNG(1990000+s*20+n),c=company(r),b=B[(s+n)%B.length],k=K[(s+n*2)%K.length],posture=P[(s*2+n)%P.length],initial=c.cash,rr=Object.fromEntries((['internal','expert','network','automation','external'] as Response[]).map(a=>[a,Array(8).fill(0)])) as Record<Response,number[]>,ir=Object.fromEntries((['river','intranet','expert_coach','cop','training','automation','aar'] as Invest[]).map(a=>[a,Array(8).fill(0)])) as Record<Invest,number[]>;let wins=0,used=0,shiftRound:number|null=null,lastDominant='';for(let round=1;round<=8;round++){for(const e of events.filter(x=>x.round===round)){const before=visible(mode,c,e.domain),pick=respond(mode,c,e,posture),ok=r.chance(pick.p);if(ok)wins++;else if(e.card.type==='problem')c.cash=Math.max(0,c.cash-e.impact);else c.cash+=0;if(pick.choice==='expert')c.expertPressure[e.domain]++;rr[pick.choice][round-1]++;logs.push({session:s,company:n,mode,round,move:e.move,phase:'challenge',choice:pick.choice,domain:e.domain,reason:pick.reason,alternatives:pick.alts,visible:before,outcome:ok?'success':'failure'});observe(c,e)}let actions=defaultActionsForMode(mode),guard=0,roundChoices:string[]=[];while(actions>0&&guard++<40){const cand=investCandidates(mode,c,b,k,posture).filter(x=>COST[x.a]<=Math.max(0,c.cash-initial*(posture==='risk_averse'?.25:posture==='bullish'?.08:.15)));const best=cand[0];if(!best||best.score<=.12)break;logs.push({session:s,company:n,mode,round,phase:'invest',choice:best.a,domain:best.d,reason:best.reason,alternatives:cand.slice(1,3).map(x=>`${x.a} ${x.score.toFixed(2)}`),visible:visible(mode,c,best.d),outcome:`spent $${COST[best.a]}k`});apply(c,best);ir[best.a][round-1]++;roundChoices.push(best.a);used++;actions--}const dominant=roundChoices.sort((a,b)=>roundChoices.filter(x=>x===b).length-roundChoices.filter(x=>x===a).length)[0]||'';if(lastDominant&&dominant&&dominant!==lastDominant&&shiftRound==null&&round>=3)shiftRound=round;if(dominant)lastDominant=dominant}const flatInvest=Object.fromEntries(Object.entries(ir).map(([a,x])=>[a,(x as number[]).reduce((q,v)=>q+v,0)])) as Record<Invest,number>;const falseLearning:string[]=[];if(flatInvest.intranet>used*.55)falseLearning.push('capture_everything');if(rr.expert.reduce((a,v)=>a+v,0)>12)falseLearning.push('always_use_expert');if(flatInvest.river>used*.55)falseLearning.push('always_use_river');if(shiftRound==null)falseLearning.push('no_strategy_shift');results.push({session:s,company:n,mode,success:wins/16,cashRatio:c.cash/initial,actionsUsed:used,actionsAvailable:8*defaultActionsForMode(mode),shiftRound,responseRound:rr,investRound:ir,falseLearning})}}
function sum(mode:Mode){const x=results.filter(r=>r.mode===mode),allLogs=logs.filter(l=>l.mode===mode),reason=[...allLogs.reduce((m,l)=>m.set(l.reason,(m.get(l.reason)||0)+1),new Map<string,number>())].sort((a,b)=>b[1]-a[1]).slice(0,10);const resp=Object.fromEntries((['internal','expert','network','automation','external'] as Response[]).map(a=>[a,Array.from({length:8},(_,i)=>x.reduce((s,r)=>s+r.responseRound[a][i],0))]));const inv=Object.fromEntries((['river','intranet','expert_coach','cop','training','automation','aar'] as Invest[]).map(a=>[a,Array.from({length:8},(_,i)=>x.reduce((s,r)=>s+r.investRound[a][i],0))]));const falseCounts=Object.fromEntries(['capture_everything','always_use_expert','always_use_river','no_strategy_shift'].map(f=>[f,x.filter(r=>r.falseLearning.includes(f)).length]));return{companies:x.length,success:mean(x.map(r=>r.success)),cashRatio:mean(x.map(r=>r.cashRatio)),actionsUsed:mean(x.map(r=>r.actionsUsed/r.actionsAvailable)),shiftRate:x.filter(r=>r.shiftRound!=null).length/x.length,meanShift:mean(x.filter(r=>r.shiftRound!=null).map(r=>r.shiftRound!)),responses:resp,investments:inv,falseLearning:falseCounts,reasons:reason}}
const summary={generatedAt:new Date().toISOString(),description:'30 eight-round games, five one-player companies: 20 Newbie and 10 Advanced. Hidden publication evidence prevents a new player-facing metric: Intranet value becomes available after knowledge proves recurring/critical through work, sharing or AAR. Late events are deliberately heterogeneous, and agents consider at most two displayed alternatives per decision to approximate a 60-minute cognitive budget.',newbie:sum('newbie'),expert:sum('expert')};mkdirSync('balance-results',{recursive:true});writeFileSync('balance-results/agent-player-study-v3.json',JSON.stringify({summary,results,logs},null,2));const md=`# Agent study V3 — cognitive-budget learning curves\n\n## Newbie\n- Success ${(summary.newbie.success*100).toFixed(1)}% · ending turnover ${(summary.newbie.cashRatio*100).toFixed(1)}% · Actions ${(summary.newbie.actionsUsed*100).toFixed(1)}%\n- Strategy shift ${(summary.newbie.shiftRate*100).toFixed(1)}%, mean round ${summary.newbie.meanShift.toFixed(1)}\n- Expert responses by round: ${(summary.newbie.responses as any).expert.join(', ')}\n- River: ${(summary.newbie.investments as any).river.join(', ')}\n- Intranet: ${(summary.newbie.investments as any).intranet.join(', ')}\n- False-learning flags: ${JSON.stringify(summary.newbie.falseLearning)}\n\n## Advanced\n- Success ${(summary.expert.success*100).toFixed(1)}% · ending turnover ${(summary.expert.cashRatio*100).toFixed(1)}% · Actions ${(summary.expert.actionsUsed*100).toFixed(1)}%\n- Strategy shift ${(summary.expert.shiftRate*100).toFixed(1)}%, mean round ${summary.expert.meanShift.toFixed(1)}\n- Expert responses by round: ${(summary.expert.responses as any).expert.join(', ')}\n- River: ${(summary.expert.investments as any).river.join(', ')}\n- Intranet: ${(summary.expert.investments as any).intranet.join(', ')}\n- False-learning flags: ${JSON.stringify(summary.expert.falseLearning)}\n\n## Common Newbie reasoning\n${summary.newbie.reasons.map(([r,n])=>`- ${n}× ${r}`).join('\n')}\n\n## Common Advanced reasoning\n${summary.expert.reasons.map(([r,n])=>`- ${n}× ${r}`).join('\n')}\n`;writeFileSync('balance-results/agent-player-study-v3.md',md);console.log('\n=== AGENT STUDY V3 ===\n',summary,'\n'+md);
