import assert from 'node:assert/strict';
import {toggleKMWeekSourceV1} from '../src/engine/kmWeekSelectionV1.ts';
import {kmWeekCoachV1} from '../src/engine/kmWeekCoachV1.ts';
import {createInitialCompanyV2} from '../src/engine/coreV2.ts';
import {DEFAULT_CONFIG} from '../src/engine/config.ts';
import {initialiseKMWeekCompanyV1,applyKMWeekActionV1} from '../src/engine/kmWeekV1.ts';
import type {GameSessionV2} from '../src/types/gameV2.ts';
assert.deepEqual(toggleKMWeekSourceV1('none','depth','local',1,5),{local:'breadth',expert:'depth'});
assert.deepEqual(toggleKMWeekSourceV1('breadth','depth','local',1,5),{local:'none',expert:'depth'});
assert.deepEqual(toggleKMWeekSourceV1('breadth','depth','expert',1,5),{local:'depth',expert:'none'});
assert.deepEqual(toggleKMWeekSourceV1('depth','none','expert',5,2),{local:'depth',expert:'breadth'});
const company=createInitialCompanyV2('Coaching test','coach',DEFAULT_CONFIG);
initialiseKMWeekCompanyV1(company);
const state=company.kmWeek!;
assert.match(kmWeekCoachV1(company)!.text,/deeper expertise/);
state.investmentHistory.push({roundLabel:'Guided 1',type:'TRAIN_EXPERT',domain:'operations',before:4,after:5});
assert.match(kmWeekCoachV1(company)!.text,/train the best site/);
state.stage='free';state.freeRound=1;company.round=4;state.phase='invest';
const expert=company.experts.find(e=>e.domains[0].domain==='operations')!;
expert.domains[0].score=4;
const site=company.sites.find(s=>s.id==='brisbane')!;
site.teamCapability.operations=3;
const session={id:'coach-session',experienceMode:'km_week',companies:[company],activeEvents:{},participants:[],timerPausedSecondsRemaining:1800} as unknown as GameSessionV2;
let result=applyKMWeekActionV1(session,company.id,{type:'KM_WEEK_INVEST',investment:'LOCAL_TRAINING',domain:'operations',siteId:site.id,expertId:expert.id});
assert.equal(result.success,true,result.message);
assert.equal(site.teamCapability.operations,4,'+2 training must stop at expert ceiling');
assert.equal(expert.domains[0].score,4,'Training staff must retain expert knowledge');
assert.equal(state.trainingCommitments?.[expert.id],company.round);
assert.match(kmWeekCoachV1(company)!.text,/busy building capability/);
state.challenges=[{id:'risk-expert',title:'Test',story:'Test',siteId:site.id,domain:'operations',difficulty:6,impact:15,status:'open'}];
result=applyKMWeekActionV1(session,company.id,{type:'KM_WEEK_RESOLVE',challengeId:'risk-expert',method:'risk',expertId:expert.id,useExpertRisk:true});
assert.equal(result.success,false,'Risk cannot bypass trainer unavailability');
state.trainingCommitments={};
state.challenges.push({...state.challenges[0],id:'second',status:'open'});
const random=Math.random;Math.random=()=>0;
try{
 result=applyKMWeekActionV1(session,company.id,{type:'KM_WEEK_RESOLVE',challengeId:'risk-expert',method:'risk',expertId:expert.id,useExpertRisk:true,useLocalRisk:true,includeLocalBreadth:true});
 assert.equal(result.success,true,result.message);
 assert.match(result.message,/performance gap 1, needed 2/,'Expert depth and local breadth must both reduce risk');
 assert.ok(state.usedExpertIds.includes(expert.id),'Risk must commit the expert for the round');
}finally{Math.random=random;}
company.round=7;assert.equal(kmWeekCoachV1(company),null);
console.log('KM Week coaching, selections and training commitment passed');
