import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, ArrowRight, BarChart3, Building2, Shield } from 'lucide-react';
import type { KnowledgeDomain, Participant } from './types/game.ts';
import type { ActiveEventV2, BusinessStrategy, CompanyV2, GameSessionV2, KnowledgeStrategy } from './types/gameV2.ts';
import { AustraliaMap } from './components/AustraliaMap.tsx';
import type { SiteImpactEffect } from './components/AustraliaMap.tsx';
import { EventDecisionCardV4 } from './components/EventDecisionCardV4.tsx';
import { SharedGameTimer } from './components/SharedGameTimer.tsx';
import { ActionsPanelV4 } from './components/ActionsPanelV4.tsx';
import { AttritionModal } from './components/AttritionModal.tsx';
import { FinalDisruptionModal } from './components/FinalDisruptionModal.tsx';
import { SessionJoinModal } from './components/SessionJoinModal.tsx';
import { StrategyPromptV2 } from './components/StrategyPromptV2.tsx';
import { FacilitatorControlRoom } from './components/FacilitatorControlRoom.tsx';
import { BoardShell } from './components/BoardShell.tsx';
import { BoardSidePanel } from './components/BoardSidePanel.tsx';
import { CompanyChartsOverlay, captureRoundSnapshot, type RoundSnapshot } from './components/CompanyChartsOverlay.tsx';
import { formatCurrency } from './utils/format.ts';

function participantFromStorage():Participant|null{const raw=localStorage.getItem('tpg_participant');if(!raw)return null;try{return JSON.parse(raw)}catch{return null}}
type StartStage='intro'|'explore'|'play';

export function AppBoardV5(){
 const [session,setSession]=useState<GameSessionV2|null>(null);
 const [participant,setParticipant]=useState<Participant|null>(()=>participantFromStorage());
 const [showJoin,setShowJoin]=useState(()=>!participantFromStorage());
 const [selectedSiteId,setSelectedSiteId]=useState('melbourne');
 const [isHQSelected,setIsHQSelected]=useState(false);
 const [selectedEventIndex,setSelectedEventIndex]=useState(0);
 const [notification,setNotification]=useState<string|null>(null);
 const [impactEffect]=useState<SiteImpactEffect|null>(null);
 const [showFacilitatorRoom,setShowFacilitatorRoom]=useState(false);
 const [startStage,setStartStage]=useState<StartStage>('play');
 const [showCharts,setShowCharts]=useState(false);
 const [showChartsIntro,setShowChartsIntro]=useState(false);
 const [chartSnapshots,setChartSnapshots]=useState<RoundSnapshot[]>([]);
 const deferUpdates=useRef(false);
 const pendingSession=useRef<GameSessionV2|null>(null);
 const toast=(message:string)=>{setNotification(message);window.setTimeout(()=>setNotification(v=>v===message?null:v),4000)};
 const selectSite=(siteId:string)=>{setSelectedSiteId(siteId);setIsHQSelected(false)};

 useEffect(()=>{const load=async()=>{const stored=localStorage.getItem('tpg_session_id');if(stored){const r=await fetch(`/api/sessions/${stored}`);if(r.ok){setSession(await r.json());return}}const r=await fetch('/api/sessions/default');if(r.ok)setSession(await r.json());setShowJoin(true)};load().catch(()=>setShowJoin(true))},[]);
 useEffect(()=>{if(!session?.id)return;const key=`tpg_start_stage_${session.id}_r${session.round}`;const stored=localStorage.getItem(key) as StartStage|null;setStartStage(stored||'intro');if(session.round>=2&&!localStorage.getItem(`tpg_charts_intro_${session.id}_r${session.round}`)){localStorage.setItem(`tpg_charts_intro_${session.id}_r${session.round}`,'1');setShowChartsIntro(true);setShowCharts(true)}},[session?.id,session?.round]);
 useEffect(()=>{if(!session?.id)return;const stream=new EventSource(`/api/sessions/${session.id}/stream`);stream.onmessage=(message)=>{try{const data=JSON.parse(message.data);if(!data.session)return;if(deferUpdates.current&&(data.type==='EVENT_RESOLVED'||data.type==='CHALLENGES_COMPLETE')){pendingSession.current=data.session;return}setSession(data.session)}catch{}};return()=>stream.close()},[session?.id]);

 const company:CompanyV2|undefined=useMemo(()=>{if(!session)return;const id=participant?.companyId||localStorage.getItem('tpg_company_id');return session.companies.find(c=>c.id===id)||session.companies[0]},[participant?.companyId,session]);
 useEffect(()=>{if(!company)return;if(!company.sites.some(s=>s.id===selectedSiteId&&!s.isClosed))setSelectedSiteId(company.sites.find(s=>!s.isClosed)?.id||'melbourne')},[company,selectedSiteId]);
 useEffect(()=>{if(!session||!company)return;const key=`tpg_chart_snapshots_${session.id}_${company.id}`;let history:RoundSnapshot[]=[];try{history=JSON.parse(localStorage.getItem(key)||'[]')}catch{}if(!history.some(s=>s.round===session.round)){history=[...history,captureRoundSnapshot(company,session.round)].sort((a,b)=>a.round-b.round);localStorage.setItem(key,JSON.stringify(history))}setChartSnapshots(history)},[session?.id,session?.round,company?.id]);

 const join=async(sessionId:string,requestedCompanyId:string,playerName:string)=>{const getRes=await fetch(`/api/sessions/${sessionId.toUpperCase()}`);if(!getRes.ok){toast('Game code not found.');return}const found:GameSessionV2=await getRes.json();const companyId=requestedCompanyId||found.companies[0]?.id;const res=await fetch(`/api/sessions/${found.id}/join`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:playerName||'Player',companyId,role:'participant'})});if(!res.ok){toast('Could not join this game.');return}const data=await res.json();setSession(data.session);setParticipant(data.participant);setShowJoin(false);setShowFacilitatorRoom(false);localStorage.setItem('tpg_session_id',data.session.id);localStorage.setItem('tpg_company_id',data.participant.companyId);localStorage.setItem('tpg_participant_id',data.participant.id);localStorage.setItem('tpg_participant',JSON.stringify(data.participant));setStartStage('intro')};
 const create=async(name:string,companyCount:number)=>{const res=await fetch('/api/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,companyCount})});if(!res.ok){toast('Could not create the game.');return}const created:GameSessionV2=await res.json();const jr=await fetch(`/api/sessions/${created.id}/join`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Facilitator',companyId:created.companies[0]?.id,role:'facilitator'})});const data=await jr.json();setSession(data.session);setParticipant(data.participant);setShowJoin(false);setShowFacilitatorRoom(false);localStorage.setItem('tpg_session_id',data.session.id);localStorage.setItem('tpg_company_id',data.participant.companyId);localStorage.setItem('tpg_participant_id',data.participant.id);localStorage.setItem('tpg_participant',JSON.stringify(data.participant));setStartStage('intro')};
 const solo=()=>create('Solo Performance Gap',1);
 const enterFacilitatorMode=async()=>{if(!session)return;const passcode=window.prompt('Facilitator passcode');if(!passcode)return;const res=await fetch(`/api/sessions/${session.id}/facilitator/override`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({passcode,updates:{}})});const data=await res.json();if(!res.ok||data.success===false){toast(data.error||data.message||'Invalid facilitator passcode.');return}const p:Participant=participant?{...participant,role:'facilitator',lastSeen:new Date().toISOString()}:{id:`fac-${Date.now()}`,sessionId:session.id,name:'Facilitator',companyId:session.companies[0]?.id||'',role:'facilitator',lastSeen:new Date().toISOString()};setParticipant(p);localStorage.setItem('tpg_participant',JSON.stringify(p));setSession(data.session||session);setShowFacilitatorRoom(true)};
 const submitStrategy=async(stage:'initial'|'final',business:BusinessStrategy,knowledge:KnowledgeStrategy)=>{if(!session||!company)return;const res=await fetch(`/api/sessions/${session.id}/strategy`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId:company.id,stage,businessStrategy:business,knowledgeStrategy:knowledge})});const data=await res.json();if(!res.ok){toast(data.error||'Could not record strategy.');return}setSession(data.session)};
 const advancePhase=async()=>{if(!session)return;const res=await fetch(`/api/sessions/${session.id}/advance-phase`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const data=await res.json();if(!res.ok||data.success===false){toast(data.message||data.error||'Cannot advance yet.');return}let next=data.session as GameSessionV2;if(next.phase==='consequences'){const r2=await fetch(`/api/sessions/${session.id}/advance-phase`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const d2=await r2.json();if(r2.ok&&d2.success!==false)next=d2.session}setSession(next);setSelectedEventIndex(0)};
 const setAllocation=async(eventId:string,domain:KnowledgeDomain,allocation:any)=>{if(!session||!company)return;const res=await fetch(`/api/sessions/${session.id}/events/allocate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId:company.id,eventInstanceId:eventId,domain,allocation})});const data=await res.json();if(!res.ok){toast(data.message||data.error||'That option is not available.');return}setSession(data.session)};
 const resolveEvent=async(eventId:string)=>{if(!session||!company)throw new Error('Game unavailable');deferUpdates.current=true;const res=await fetch(`/api/sessions/${session.id}/resolve-event`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId:company.id,eventInstanceId:eventId})});const data=await res.json();if(!res.ok){deferUpdates.current=false;throw new Error(data.message||data.error||'Event could not be resolved.')}pendingSession.current=data.session;return data};
 const acknowledgeResolution=async(data:any)=>{
  if(!session||!company)throw new Error('Game unavailable');
  deferUpdates.current=false;
  let next=(data?.session||pendingSession.current) as GameSessionV2|undefined;
  pendingSession.current=null;
  if(!next){const fresh=await fetch(`/api/sessions/${session.id}`);if(!fresh.ok)throw new Error('Could not refresh the game state.');next=await fresh.json()}
  const nextEvents:ActiveEventV2[]=next.activeEvents[company.id]||[];
  const unresolved=nextEvents.findIndex(e=>!e.isResolved);
  if(unresolved>=0){setSession(next);setSelectedEventIndex(unresolved);const target=nextEvents[unresolved].targetSiteId;if(target)selectSite(target);return}
  if(next.phase==='respond'){
   const r=await fetch(`/api/sessions/${next.id}/advance-phase`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const d=await r.json();
   if(!r.ok||d.success===false)throw new Error(d.message||d.error||'Could not finish the Challenge stage.');
   next=d.session;
  }
  if(next.phase==='consequences'){
   const r=await fetch(`/api/sessions/${next.id}/advance-phase`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const d=await r.json();
   if(!r.ok||d.success===false)throw new Error(d.message||d.error||'Could not move to Invest.');
   next=d.session;
  }
  setSession(next);setSelectedEventIndex(0);
 };
 const redrawEvent=async(eventId:string)=>{if(!session||!company)return;const res=await fetch(`/api/sessions/${session.id}/redraw-event`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId:company.id,eventInstanceId:eventId})});const data=await res.json();if(!res.ok){toast(data.message||data.error||'Redraw not available.');return}setSession(data.session)};
 const performAction=async(actionType:string,params:any={})=>{if(!session||!company)return;const res=await fetch(`/api/sessions/${session.id}/action`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId:company.id,actionType,params})});const data=await res.json();if(!res.ok){toast(data.message||data.error||'Action unavailable.');return}setSession(data.session);toast(data.message||'Action completed.')};

 if(!session||!company)return <div className="min-h-screen bg-slate-950 text-white grid place-items-center">Loading The Performance Gap…</div>;
 const events=session.activeEvents[company.id]||[];const firstUnresolved=events.findIndex(e=>!e.isResolved);const activeEventIndex=firstUnresolved>=0?firstUnresolved:Math.min(selectedEventIndex,Math.max(0,events.length-1));const selectedEvent=events[activeEventIndex];
 const isFacilitator=participant?.role==='facilitator';const horizonCanRedraw=selectedEvent&&company.horizonScanAvailableRound===session.round&&!company.horizonScanUsedThisRound&&!!company.horizonScanDomain&&selectedEvent.card.domains.some(r=>r.domain===company.horizonScanDomain);
 const needsInitialStrategy=!!participant&&session.round===1&&startStage==='explore'&&!company.knowledgeStrategyInitial&&(!isFacilitator||session.companies.length===1);const needsFinalStrategy=!!participant&&!isFacilitator&&!!session.finalDisruptionResolved&&!company.knowledgeStrategyFinal;
 const setStage=(stage:StartStage)=>{setStartStage(stage);localStorage.setItem(`tpg_start_stage_${session.id}_r${session.round}`,stage)};
 const ownComplete=events.length>0&&events.every(e=>e.isResolved);const otherIncomplete=session.companies.filter(c=>c.id!==company.id).filter(c=>(session.activeEvents[c.id]||[]).some(e=>!e.isResolved)).length;
 const taskStatus=!ownComplete?'Complete your tasks below':otherIncomplete>0?`Waiting on ${otherIncomplete} other team${otherIncomplete===1?'':'s'}`:'All teams complete';
 const board=<AustraliaMap company={company} selectedSiteId={isHQSelected?null:selectedSiteId} onSelectSite={selectSite} onSelectHQ={()=>setIsHQSelected(true)} isHQSelected={isHQSelected} onSelectExpert={()=>undefined} impactEffect={impactEffect}/>;
 const sidePanel=<BoardSidePanel session={session} company={company} selectedSiteId={selectedSiteId} isHQSelected={isHQSelected} currentEvent={session.phase==='respond'?selectedEvent:undefined} onSelectSite={selectSite} onSelectHQ={()=>setIsHQSelected(true)}/>;
 let overlay:React.ReactNode=null;
 if(startStage==='intro')overlay=<div className="w-full max-w-2xl mx-auto mt-12 rounded-3xl border-2 border-indigo-500 bg-slate-950/95 p-6 shadow-2xl"><div className="text-xs uppercase tracking-[0.18em] text-indigo-300 font-black">{session.round===1?'Game Start':`Round ${session.round} Start`}</div><h2 className="text-2xl font-black text-white mt-2">{session.round===1?'Welcome to the Performance Gap Game.':`Review how your company enters Round ${session.round}.`}</h2>{session.round===1?<><p className="text-sm text-slate-300 mt-3 leading-relaxed">Knowledge Management Is about way more than knowledge hubs and call centre articles. Good KM helps an organisation preserve and build capability over time. Investing in training and plant helps increase capacity but local knowledge, resigning experts and low frequency, high impact problems sap an organisation's effectiveness. This game lets you find ways to overcome them.</p><p className="text-sm text-slate-300 mt-3 leading-relaxed">Build your knowledge capability through multiple rounds, and prepare for the final challange round to see who can build the strongest company.</p></>:<p className="text-sm text-slate-300 mt-3 leading-relaxed">Before the next challenges arrive, look around the organisation. Check which sites and knowledge domains have strengthened, where capability has fallen, and where risk is accumulating. From Round 2 onward the Charts view helps you see these changes over time.</p>}<button onClick={()=>setStage('explore')} className="mt-5 w-full rounded-xl bg-indigo-500 text-white py-3 font-black">{session.round===1?'START GAME':'START ROUND'}</button></div>;
 else if(startStage==='play'&&session.phase==='respond'&&!session.isFinalDisruptionActive&&selectedEvent)overlay=<div className="w-full max-w-[980px] pr-2"><EventDecisionCardV4 session={session} company={company} event={selectedEvent} cardNumber={activeEventIndex+1} onSetAllocation={setAllocation} onResolveEvent={resolveEvent} onAcknowledgeResolution={acknowledgeResolution} onRedrawEvent={redrawEvent} canHorizonRedraw={!!horizonCanRedraw}/></div>;
 else if(session.phase==='investment')overlay=<ActionsPanelV4 session={session} company={company} onPerformAction={performAction} onNextPhase={advancePhase}/>;
 else if(session.phase==='risk')overlay=<div className="w-full"><AttritionModal session={session} company={company} phaseResult={{attritionSummaries:session.riskResults||{}}} onAdvanceToNextRound={advancePhase}/></div>;

 const startLabel=session.round===1?'Game Start':'Round Start';const steps=[startLabel,'Challenges','Invest','Knowledge Risk'];const currentStep=startStage!=='play'?0:session.phase==='respond'?1:session.phase==='investment'?2:3;
 return <div className="min-h-screen bg-[#080b12] text-slate-200"><header className="sticky top-0 z-40 border-b border-slate-800 bg-[#0d111b]/95 backdrop-blur px-4 py-3"><div className="max-w-[1500px] mx-auto flex items-center justify-between gap-3"><div><div className="text-xs uppercase tracking-[0.22em] text-indigo-400 font-black">The Performance Gap</div><div className="flex items-center gap-2 mt-1"><Building2 className="w-5 h-5 text-slate-400"/><h1 className="text-xl font-black text-white">{showFacilitatorRoom?'Facilitator Control Room':company.name}</h1><span className="text-xs text-slate-500">Session {session.id}</span></div></div><div className="flex items-center gap-3">{session.round>=2&&!showFacilitatorRoom&&<button onClick={()=>{setShowChartsIntro(false);setShowCharts(true)}} className="rounded-xl border border-indigo-700 bg-indigo-950/50 px-3 py-2 text-xs font-black text-indigo-200 flex items-center gap-2"><BarChart3 className="w-4 h-4"/>Charts</button>}{!isFacilitator?<button onClick={enterFacilitatorMode} className="rounded-xl border border-indigo-700 bg-indigo-950/50 px-3 py-2 text-xs font-black text-indigo-200 flex items-center gap-2"><Shield className="w-4 h-4"/>Facilitator</button>:<button onClick={()=>setShowFacilitatorRoom(v=>!v)} className="rounded-xl border border-indigo-700 bg-indigo-950/50 px-3 py-2 text-xs font-black text-indigo-200 flex items-center gap-2"><Shield className="w-4 h-4"/>{showFacilitatorRoom?'Return to game':'Control Room'}</button>} {!showFacilitatorRoom&&<div className="rounded-2xl bg-slate-900 border border-slate-700 px-4 py-2"><div className="text-[10px] uppercase text-slate-500 font-bold">Turnover</div><div className="text-xl font-black text-white">{formatCurrency(company.turnover)}</div></div>}<SharedGameTimer session={session} isFacilitator={isFacilitator} onSessionUpdate={setSession}/></div></div></header>
 <main className="max-w-[1500px] mx-auto px-4 py-4 space-y-4"><section className="rounded-2xl border border-slate-800 bg-slate-900/60 px-4 py-3 flex items-center justify-between"><div className="flex items-center gap-2">{steps.map((s,i)=><React.Fragment key={`${s}-${i}`}><div className={`rounded-full px-4 py-2 text-sm font-black ${i===currentStep?'bg-indigo-500 text-white':i<currentStep?'bg-emerald-950 text-emerald-300 border border-emerald-800':'bg-slate-950 text-slate-600 border border-slate-800'}`}>{s}</div>{i<steps.length-1&&<ArrowRight className="w-4 h-4 text-slate-700"/>}</React.Fragment>)}</div><div className="flex items-center gap-3">{startStage==='explore'?<button onClick={()=>setStage('play')} className="rounded-xl bg-indigo-500 px-5 py-2.5 text-sm font-black text-white">Next Step <ArrowRight className="inline w-4 h-4 ml-1"/></button>:<span className="rounded-full px-3 py-1.5 text-xs font-black bg-slate-950 border border-slate-700">{session.phase==='respond'?taskStatus:'Round in progress'}</span>}<span className="font-bold text-white">Round {Math.min(session.round,session.config.rounds)} of {session.config.rounds}</span></div></section>{showFacilitatorRoom?<FacilitatorControlRoom session={session} onSessionUpdate={setSession} onToast={toast}/>:<BoardShell board={board} sidePanel={sidePanel} overlay={overlay}/>}</main>
 {showCharts&&session.round>=2&&<CompanyChartsOverlay company={company} snapshots={chartSnapshots} onClose={()=>{setShowCharts(false);setShowChartsIntro(false)}} showIntro={showChartsIntro}/>} {showJoin&&<SessionJoinModal currentSession={session} onJoinSession={join} onCreateNewSession={create} onSoloStart={solo}/>} {needsInitialStrategy&&<StrategyPromptV2 stage="initial" onSubmit={(b,k)=>submitStrategy('initial',b,k)}/>} {needsFinalStrategy&&<StrategyPromptV2 stage="final" originalBusinessStrategy={company.businessStrategyInitial} originalKnowledgeStrategy={company.knowledgeStrategyInitial} onSubmit={(b,k)=>submitStrategy('final',b,k)}/>} {session.isFinalDisruptionActive&&<FinalDisruptionModal session={session} company={company} onResolveFinalDisruption={async()=>{const res=await fetch(`/api/sessions/${session.id}/resolve-final-disruption`,{method:'POST'});const data=await res.json();if(data.session)setSession(data.session)}} onOpenAAR={()=>toast('AAR evidence is being captured.')}/>} {notification&&<div className="fixed bottom-5 right-5 z-[120] rounded-2xl bg-white text-slate-950 px-5 py-3 shadow-2xl font-bold max-w-md flex gap-2"><AlertTriangle className="w-5 h-5 text-amber-600 shrink-0"/>{notification}</div>}</div>;
}
export default AppBoardV5;
